"Resource/UI/ClassSelection.res"
{
	"class"
	{
		"controlname"	"Frame"
		"fieldname"	"class"
		
		"xpos"		"0"
		"ypos"		"0"
		
		"wide"		"f0"
		"tall"		"f0"
		
		"visible"	"1"
	}
		
	"bg"
	{		
		"controlname"	"EditablePanel"
		"fieldname"		"bg"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-2"
		"wide"					"f0"
		"tall"					"f0"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"bgcolor_override"		"BackgroundTransparent"
	}

	"Stripe"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"Stripe"
		"xpos"			"cs-0.5"
		"ypos"			"c-22"
		"zpos"			"-1"
		"wide"			"f0"
		"tall"			"165"
		"visible"		"1"
		"enabled"		"1"
		"bgcolor_override"	"TransparentStripe"
	}

	"SysMenu"
	{
		"controlname"	"Menu"
		"fieldname"		"SysMenu"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"64"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"	"0"
	}

	"PrevOptionHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"PrevOptionHintIcon"
		"xpos"			"c-250"
		"ypos"			"135"
		"wide"			"25"
		"tall"			"25"
		"zpos"			"4"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_left"
	}

	"NextOptionHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"NextOptionHintIcon"
		"xpos"			"c225"
		"ypos"			"135"
		"wide"			"25"
		"tall"			"25"
		"zpos"			"4"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"east"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_right"
	}	
	
	"classBg"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"classBg"
		"xpos"			"cs-0.5"
		"ypos"			"c-126"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"66"
		"visible"		"1"
		"enabled"		"1"
		"image"			"..\darhud\square\square_neutral"
		"teambg_0"		"..\darhud\square\square_neutral"
		"teambg_1"		"..\darhud\square\square_spectator"
		"teambg_2"		"..\darhud\square\square_red"
		"teambg_3"		"..\darhud\square\square_blue"
		"teambg_4"		"..\darhud\square\square_green"
		"teambg_5"		"..\darhud\square\square_yellow"
		"scaleimage"	"1"
	}	

	"random"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"random"
		"xpos"				"r55"
		"ypos"				"c-118"
		"zpos"				"6"
		"wide"				"48"
		"tall"				"48"
		"zpos"				"6"
		"wide"				"50"
		"tall"				"100"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			""
		"textAlignment"		"south-west"
		"Command"			"select 12"
		"Default"			"1"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_random_inactive"
		"image_armed"		"class_sel_sm_random_inactive"
		
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"		
		
		"paintbackground"	"1"
		
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		

		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"0"
			"ypos"			"-28"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_random_inactive"
			"scaleimage"	"1"
		}				
	}
	"randomShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"randomShadow"
		"pin_to_sibling"	"random"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"48"
		"tall"			"48"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"1"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
	}

	"RandomHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"RandomHintIcon"
		"pin_to_sibling" "random"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"-6"
		"wide"			"19"
		"tall"			"19"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
	}
		
	"Offense"
	{
		"visible"		"0"
		"enabled"		"0"
	}

	"scout"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"scout"
		"xpos"				"c-210"
		"ypos"				"c-115"
		"zpos"				"6"
		"wide"				"40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"1"
		"textAlignment"		"north-west"
		"Command"			"select 1"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_scout_inactive"
		"image_armed"		"class_sel_sm_scout_inactive"
		
		"image_drawcolor"		"255 255 255 180"
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"fgcolor"			"TanDark"
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"
			
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		
		"paintbackground"	"1"
		"fgcolor"			"0 0 0 192"
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"		
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"-2"
			"ypos"			"-35"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_scout_inactive"
			"scaleimage"	"1"
		}		
	}
	"scoutShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"scoutShadow"
		"pin_to_sibling"	"scout"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"40"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"1"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
	}

	"ScoutHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"ScoutHintIcon"
		"pin_to_sibling" "scout"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"wide"			"17"
		"tall"			"17"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
	}

	"soldier"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"soldier"
		"xpos"				"c-165"
		"ypos"				"c-115"
		"zpos"				"6"
		"wide"				"40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"2"
		"textAlignment"		"north-west"
		"Command"			"select 3"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_soldier_inactive"
		"image_armed"		"class_sel_sm_soldier_inactive"
		
		"image_drawcolor"		"255 255 255 180"
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"

		"fgcolor"			"TanDark"
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		
		"paintbackground"	"1"
		"fgcolor"			"0 0 0 192"
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"-2"
			"ypos"			"-30"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_soldier_inactive"
			"scaleimage"	"1"
		}				
	}
	"soldierShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"soldierShadow"
		"pin_to_sibling"	"soldier"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"40"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"1"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
	}

	"SoldierHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"SoldierHintIcon"
		"pin_to_sibling" "soldier"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"wide"			"17"
		"tall"			"17"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
	}

	"pyro"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"pyro"
		"xpos"				"c-120"
		"ypos"				"c-115"
		"zpos"				"6"
		"wide"				"40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"3"
		"textAlignment"		"north-west"
		"Command"			"select 7"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_pyro_inactive"
		"image_armed"		"class_sel_sm_pyro_inactive"
		
		"image_drawcolor"		"255 255 255 180"
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"fgcolor"			"TanDark"
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		
		"paintbackground"	"1"
		"fgcolor"			"0 0 0 192"
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"0"
			"ypos"			"-33"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_pyro_inactive"
			"scaleimage"	"1"
		}				
	}
	"pyroShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"pyroShadow"
		"pin_to_sibling"	"pyro"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"40"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"1"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
	}

	"PyroHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"PyroHintIcon"
		"pin_to_sibling" "pyro"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"wide"			"17"
		"tall"			"17"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
	}

	"Defense"
	{
		"visible"		"0"
		"enabled"		"0"
	}

	"demoman"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"demoman"
		"xpos"				"c-65"
		"ypos"				"c-115"
		"zpos"				"6"
		"wide"				"40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"4"
		"textAlignment"		"north-west"
		"Command"			"select 4"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_demo_inactive"
		"image_armed"		"class_sel_sm_demo_inactive"
		
		"image_drawcolor"		"255 255 255 180"
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"fgcolor"			"TanDark"
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"

		"paintbackground"	"1"
		"fgcolor"			"0 0 0 192"
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"-3"
			"ypos"			"-28"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_demo_inactive"
			"scaleimage"	"1"
		}				
	}
	"demomanShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"demomanShadow"
		"pin_to_sibling"	"demoman"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"40"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"1"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
	}

	"DemomanHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"DemomanHintIcon"
		"pin_to_sibling" "demoman"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"wide"			"17"
		"tall"			"17"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
	}
		
	"heavyweapons"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"heavyweapons"
		"xpos"				"c-20"
		"ypos"				"c-115"
		"zpos"				"6"
		"wide"				"40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"5"
		"textAlignment"		"north-west"
		"proportionaltoparent"	"1"
		"Command"			"select 6"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_heavy_inactive"
		"image_armed"		"class_sel_sm_heavy_inactive"

		"image_drawcolor"		"255 255 255 180"
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"fgcolor"			"TanDark"
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		
		"paintbackground"	"1"
		"fgcolor"			"0 0 0 192"
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"-2"
			"ypos"			"-25"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_heavy_inactive"
			"scaleimage"	"1"
		}				
	}
	"heavyweaponsShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"heavyweaponsShadow"
		"pin_to_sibling"	"heavyweapons"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"40"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"1"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
	}

	"HeavyHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"HeavyHintIcon"
		"pin_to_sibling" "heavyweapons"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"wide"			"17"
		"tall"			"17"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
	}

	"engineer"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"engineer"
		"xpos"				"c25"
		"ypos"				"c-115"
		"zpos"				"6"
		"wide"				"40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"6"
		"textAlignment"		"north-west"
		"Command"			"select 9"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_engineer_inactive"
		"image_armed"		"class_sel_sm_engineer_inactive"
		
		"image_drawcolor"		"255 255 255 180"
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"fgcolor"			"TanDark"
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		
		"paintbackground"	"1"
		"fgcolor"			"0 0 0 192"
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"-5"
			"ypos"			"-32"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_engineer_inactive"
			"scaleimage"	"1"
		}				
	}
	"engineerShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"engineerShadow"
		"pin_to_sibling"	"engineer"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"40"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"1"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
	}

	"EngineerHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"EngineerHintIcon"
		"pin_to_sibling" "engineer"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"wide"			"17"
		"tall"			"17"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
	}
	
	"Support"
	{
		"visible"		"0"
		"enabled"		"0"
	}

	"medic"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"medic"
		"xpos"				"c80"
		"ypos"				"c-115"
		"zpos"				"6"
		"wide"				"40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"7"
		"textAlignment"		"north-west"
		"Command"			"select 5"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_medic_inactive"
		"image_armed"		"class_sel_sm_medic_inactive"
		
		"image_drawcolor"		"255 255 255 180"
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"fgcolor"			"TanDark"
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		
		"paintbackground"	"1"
		"fgcolor"			"0 0 0 192"
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"-2"
			"ypos"			"-25"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_medic_inactive"
			"scaleimage"	"1"
		}				
	}
	"medicShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"medicShadow"
		"pin_to_sibling"	"medic"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"40"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"1"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
	}

	"MedicHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"MedicHintIcon"
		"pin_to_sibling" "medic"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"wide"			"17"
		"tall"			"17"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
	}

	"sniper"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"sniper"
		"xpos"				"c125"
		"ypos"				"c-115"
		"zpos"				"6"
		"wide"				"40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"8"
		"textAlignment"		"north-west"
		"Command"			"select 2"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_sniper_inactive"
		"image_armed"		"class_sel_sm_sniper_inactive"
		
		"image_drawcolor"		"255 255 255 180"
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"fgcolor"			"TanDark"
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		
		"paintbackground"	"1"
		"fgcolor"			"0 0 0 192"
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"-5"
			"ypos"			"-22"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_sniper_inactive"
			"scaleimage"	"1"
		}				
	}
	"sniperShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"sniperShadow"
		"pin_to_sibling"	"sniper"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"40"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"1"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
	}

	"SniperHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"SniperHintIcon"
		"pin_to_sibling" "sniper"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"wide"			"17"
		"tall"			"17"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
	}

	"spy"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"spy"
		"xpos"				"c170"
		"ypos"				"c-115"
		"zpos"				"6"
		"wide"				"40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"9"
		"textAlignment"		"north-west"
		"Command"			"select 8"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_spy_inactive"
		"image_armed"		"class_sel_sm_spy_inactive"
		
		"image_drawcolor"		"255 255 255 180"
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"fgcolor"			"TanDark"
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		
		"paintbackground"	"1"
		"fgcolor"			"0 0 0 192"
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"-4"
			"ypos"			"-27"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_spy_inactive"
			"scaleimage"	"1"
		}				
	}
	"spyShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"spyShadow"
		"pin_to_sibling"	"spy"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"40"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"1"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
	}

	"SpyHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"SpyHintIcon"
		"pin_to_sibling" "spy"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"wide"			"17"
		"tall"			"17"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
	}

	"civilian"
	{
		"controlname"		"CEximageButton"
		"fieldname"			"civilian"
		"xpos"				"c240"
		"ypos"				"c-115"
		"zpos"				"6"
		"wide"				"40"
		"tall"				"40"
		"autoResize"		"0"
		"pinCorner"			"2"
		"visible"			"0"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"#dar_blank"
		"textAlignment"		"north-west"
		"Command"			"select 10"
		"Default"			"0"
		"font"				"MenuKeys"
		"scaleimage"		"1"
		
		"image_default"		"class_sel_sm_spy_inactive"
		"image_armed"		"class_sel_sm_spy_inactive"
		
		"image_drawcolor"		"255 255 255 180"
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"fgcolor"			"TanDark"
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		
		"paintbackground"	"1"
		"fgcolor"			"0 0 0 192"
		"defaultbgColor_override" "0 0 0 192"
		"armedbgColor_override" "0 0 0 192"
		"depressedbgColor_override" "0 0 0 192"
		"selectedbgColor_override" "20 20 20 250"
		
		"stayselectedonclick"	"1"
		"selectonhover"			"1"
		"keyboardinputenabled"	"0"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"-4"
			"ypos"			"-27"
			"zpos"			"7"
			"wide"			"50"
			"tall"			"100"
			"visible"		"1"
			"enabled"		"1"
			"image"			"class_sel_sm_spy_inactive"
			"scaleimage"	"1"
		}
		"if_special_classes"
		{
			"visible"			"1"
		}
	}
	"civilianShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"civilianShadow"
		"pin_to_sibling"	"civilian"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"40"
		"image"			"../darhud/square_shadow_corner"
		"scaleimage"		"1"
		"visible"		"0"
		
		"src_corner_width"	"1"
		"src_corner_height"	"1"
		"draw_corner_width"	"2"
		"draw_corner_height" 	"2"
		
		"if_special_classes"
		{
				"visible"			"1"
		}
	}

	"CivilianHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"CivilianHintIcon"
		"pin_to_sibling" "civilian"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"wide"			"17"
		"tall"			"17"
		"zpos"			"9"
		"autoResize"	"0"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"south-west"
		"pinCorner"		"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_select"
		
		"if_special_classes"
		{
			"visible"			"1"
		}
	}

	"CancelButton" [$WIN32] 
	{
		"controlname"	"CExButton"
		"fieldname"		"CancelButton"
		"xpos"			"c-295"
		"ypos"			"r38"
		"zpos"			"6"
		"wide"			"120"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_ClassMenu_Cancel_NoKey"
		"textAlignment"	"center"
		"Command"		"vguicancel"
		"font"			"HudFontSmallBold"
		"fgcolor_override" "200 80 60 255"
	}

	"CancelHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"CancelHintIcon"
		"xpos"			"c-290"
		"ypos"			"r38"
		"zpos"			"7"
		"wide"			"25"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_cancel"
	}
	
	"EditLoadoutButton" [$WIN32] 
	{
		"controlname"	"CExButton"
		"fieldname"		"EditLoadoutButton"
		"xpos"			"r180"
		"ypos"			"r38"
		"zpos"			"6"
		"wide"			"165"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#EditLoadout"
		"textAlignment"	"center"
		"Command"		"openloadout"
		"font"			"HudFontSmallBold"
	}
	"EditLoadoutButtonCopy"
	{
		"controlname"	"CEximageButton"
		"fieldname"		"EditLoadoutButtonCopy"
		"xpos"			"5"
		"ypos"			"c-115"
		"zpos"			"6"
		"wide"			"48"
		"tall"			"48"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"	"0"
		"labelText"		""
		"textAlignment"	"center"
		"Command"		"openloadout"
		"font"			"HudFontSmallBold"
		"roundedcorners"	"0"			
		
		"image_default"		"../hud/backpack_01_grey"
		"image_armed"		"../hud/backpack_01_grey"
		
		"image_armedcolor"		"255 255 255 255"
		"image_selectedcolor"	"255 255 255 255"
		
		"defaultFgColor_override" "TanDark"
		"armedFgColor_override" "TanDark"
		"depressedFgColor_override" "TanDark"
		"selectedFgColor_override" "White"		
		
		"paintbackground"	"1"
		
		"dropshadow"	"0"
		
		"defaultbgColor_override" "0 0 0 0"
		"armedbgColor_override" "20 20 20 0"
		"depressedbgColor_override" "0 0 0 0"
		"selectedbgColor_override" "20 20 20 0"
		
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"sound_armed"		"UI/buttonrollover.wav"
		
		"Subimage"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Subimage"
			"xpos"			"3"
			"ypos"			"5"
			"zpos"			"7"
			"wide"			"42"
			"tall"			"42"
			"visible"		"1"
			"enabled"		"1"
			"image"			"../hud/backpack_01_grey"
			"scaleimage"	"1"
		}
	}

	"EditLoadoutHintIcon"
	{
		"controlname"	"CSCHintIcon"
		"fieldname"		"EditLoadoutHintIcon"
		"xpos"			"r176"
		"ypos"			"r38"
		"zpos"			"7"
		"wide"			"25"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
		"actionSet"		"InGameHUDControls"
		"actionName"	"menu_toggle_function"
	}

	"ResetButton" [$WIN32] 
	{
		"controlname"	"CExButton"
		"fieldname"		"ResetButton"
		"xpos"			"r470"
		"ypos"			"r38"
		"zpos"			"6"
		"wide"			"110"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_ClassMenu_Reset"
		"textAlignment"	"center"
		"Command"		"resetclass"
		"font"			"HudFontSmallBold"
	}

	"ClassMenuSelect"
	{
		"controlname"	"CExLabel"
		"fieldname"		"ClassMenuSelect"
		"xpos"			"30"
		"xpos_lodef"			"62"
		"xpos_hidef"			"72"
		"ypos"			"r40"
		"ypos_lodef"			"r60"
		"ypos_hidef"			"r54"
		"zpos"			"5"
		"wide"			"450"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"visible_lodef"	"0"
		"enabled"		"1"
		"labelText"		"#TF_SelectAClass"
		"textAlignment"	"west"
		"font"			"MenuMainTitle"
		"fgcolor"		"HudOffWhite"
	}
	
	"MenuBG"
	{	
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
	}	

	"Hint"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"Hint"
		"xpos"			"c-300"
		"ypos"			"95"
		"zpos"			"2"
		"wide"			"600"
		"tall"			"50"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%hint%"
		"textAlignment"	"west"
		"wrap"			"1"
		"font"			"HudFontMediumSmallSecondary"
		"fgcolor"		"GeneralLabel"
	}
	
	"ShadedBar"
	{
		"visible"		"0"
		"enabled"		"0"
	}
	
	"localPlayerimage"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"localPlayerimage"
		"xpos"			"c-130"
		"ypos"			"r100"
		"zpos"			"15"
		"wide"			"45"
		"tall"			"90"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"localPlayerBG"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"localPlayerBG"
		"xpos"			"c-135"
		"ypos"			"r80"
		"zpos"			"15"
		"wide"			"50"
		"tall"			"70"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/color_panel_clear"
		"scaleimage"	"1"
		"teambg_2"		"../hud/color_panel_clear"
		"teambg_3"		"../hud/color_panel_clear"
			
		"src_corner_height"		"50"			// pixels inside the image
		"src_corner_width"		"50"
				
		"draw_corner_width"		"5"				// screen size of the corners ( and sides ), proportional
		"draw_corner_height" 	"5"	
	}
	
	"countimage0"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage0"
		"xpos"			"c-90"
		"ypos"			"r90"
		"zpos"			"14"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}							
	
	"countimage1"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage1"
		"xpos"			"c-75"
		"ypos"			"r90"
		"zpos"			"13"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"countimage2"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage2"
		"xpos"			"c-60"
		"ypos"			"r90"
		"zpos"			"12"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"countimage3"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage3"
		"xpos"			"c-45"
		"ypos"			"r90"
		"zpos"			"11"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"countimage4"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage4"
		"xpos"			"c-30"
		"ypos"			"r90"
		"zpos"			"10"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"countimage5"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage5"
		"xpos"			"c-15"
		"ypos"			"r90"
		"zpos"			"9"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"countimage6"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage6"
		"xpos"			"c0"
		"ypos"			"r90"
		"zpos"			"8"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"countimage7"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage7"
		"xpos"			"c15"
		"ypos"			"r90"
		"zpos"			"7"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"countimage8"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage8"
		"xpos"			"c30"
		"ypos"			"r90"
		"zpos"			"6"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"countimage9"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage9"
		"xpos"			"c45"
		"ypos"			"r90"
		"zpos"			"5"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"countimage10"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"countimage10"
		"xpos"			"c60"
		"ypos"			"r90"
		"zpos"			"4"
		"wide"			"40"
		"tall"			"80"
		"visible"		"0"
		"enabled"		"1"
		"image"			""	
		"scaleimage"	"1"
	}
	
	"CountLabel1"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CountLabel1"
		"xpos"			"cs-0.5"
		"ypos"			"380"
		"zpos"			"10"
		"wide"			"250"
		"tall"			"18"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#TF_TeamCount"
		"textAlignment"	"center"
		"font"			"HudFontMediumSmallSecondary"
		"fgcolor"		"GeneralLabel"
	}
	
	"CountLabel"
	{
		"visible"		"0"
		"enabled"		"0"
	}
	
	"numScout"
	{
		"controlname"	"CExLabel"
		"fieldname"		"numScout"
		"pin_to_sibling"	"scout"
		"pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"30"
		"tall"			"12"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%numScout%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"GeneralLabel"
		"mouseinputenabled"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		"textinsetx"	"0"
	}	
	
	"numSoldier"
	{
		"controlname"	"CExLabel"
		"fieldname"		"numSoldier"
		"pin_to_sibling"	"soldier"
		"pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"30"
		"tall"			"12"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%numSoldier%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"GeneralLabel"
		"mouseinputenabled"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		"textinsetx"	"0"
	}		
	
	"numPyro"
	{
		"controlname"	"CExLabel"
		"fieldname"		"numPyro"
		"pin_to_sibling"	"pyro"
		"pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"30"
		"tall"			"12"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%numPyro%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"GeneralLabel"
		"mouseinputenabled"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		"textinsetx"	"0"
	}			
	
	"numDemoman"
	{
		"controlname"	"CExLabel"
		"fieldname"		"numDemoman"
		"pin_to_sibling"	"demoman"
		"pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"30"
		"tall"			"12"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%numDemoman%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"GeneralLabel"
		"mouseinputenabled"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		"textinsetx"	"0"
	}				
	
	"numHeavy"
	{
		"controlname"	"CExLabel"
		"fieldname"		"numHeavy"
		"pin_to_sibling"	"heavyweapons"
		"pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"30"
		"tall"			"12"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%numHeavy%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"GeneralLabel"
		"mouseinputenabled"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		"textinsetx"	"0"
	}	
	
	"numEngineer"
	{
		"controlname"	"CExLabel"
		"fieldname"		"numEngineer"
		"pin_to_sibling"	"engineer"
		"pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"30"
		"tall"			"12"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%numEngineer%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"GeneralLabel"
		"mouseinputenabled"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		"textinsetx"	"0"
	}					
	
	"numMedic"
	{
		"controlname"	"CExLabel"
		"fieldname"		"numMedic"
		"pin_to_sibling"	"medic"
		"pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"30"
		"tall"			"12"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%numMedic%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"GeneralLabel"
		"mouseinputenabled"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		"textinsetx"	"0"
	}							
	
	"numSniper"
	{
		"controlname"	"CExLabel"
		"fieldname"		"numSniper"
		"pin_to_sibling"	"sniper"
		"pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"30"
		"tall"			"12"
		"tall"			"12"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%numSniper%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"GeneralLabel"
		"mouseinputenabled"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		"textinsetx"	"0"
	}
	
	"numSpy"
	{
		"controlname"	"CExLabel"
		"fieldname"		"numSpy"
		"pin_to_sibling"	"spy"
		"pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"30"
		"tall"			"12"
		"tall"			"12"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%numSpy%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"GeneralLabel"
		"mouseinputenabled"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		"textinsetx"	"0"
	}
	
	"numCivilian"
	{
		"controlname"	"CExLabel"
		"fieldname"		"numCivilian"
		"pin_to_sibling"	"civilian"
		"pin_corner_to_sibling" "PIN_CENTER_BOTTOM"
		"pin_to_sibling_corner" "PIN_CENTER_TOP"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"8"
		"wide"			"30"
		"tall"			"12"
		"tall"			"12"
		"autoResize"	"1"
		"pinCorner"		"2"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%numCivilian%"
		"textAlignment"	"center"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"GeneralLabel"
		"mouseinputenabled"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		"textinsetx"	"0"
		
		"if_special_classes"
		{
			"visible"			"1"
		}
	}
	
	"MvMUpgradeimageScout"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MvMUpgradeimageScout"
		"pin_to_sibling"	"scout"
		"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"10"
		"wide"			"12"
		"tall"			"12"
		"visible"		"0"
		"enabled"		"1"
		"image"			"mvm/class_upgraded"
		"scaleimage"	"1"
	}
	
	"MvMUpgradeimageSolider"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MvMUpgradeimageSolider"
		"pin_to_sibling"	"soldier"
		"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"10"
		"wide"			"12"
		"tall"			"12"
		"visible"		"0"
		"enabled"		"1"
		"image"			"mvm/class_upgraded"
		"scaleimage"	"1"
	}
	
	"MvMUpgradeimagePyro" 
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MvMUpgradeimagePyro" 
		"pin_to_sibling"	"pyro"
		"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"10"
		"wide"			"12"
		"tall"			"12"
		"visible"		"0"
		"enabled"		"1"
		"image"			"mvm/class_upgraded"
		"scaleimage"	"1"
	}
	
	"MvMUpgradeimageDemoman" 
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MvMUpgradeimageDemoman" 
		"pin_to_sibling"	"demoman"
		"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"10"
		"wide"			"12"
		"tall"			"12"
		"visible"		"0"
		"enabled"		"1"
		"image"			"mvm/class_upgraded"
		"scaleimage"	"1"
	}
	
	"MvMUpgradeimageHeavy"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MvMUpgradeimageHeavy" 
		"pin_to_sibling"	"heavyweapons"
		"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"10"
		"wide"			"12"
		"tall"			"12"
		"visible"		"0"
		"enabled"		"1"
		"image"			"mvm/class_upgraded"
		"scaleimage"	"1"
	}
	
	"MvMUpgradeimageEngineer"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MvMUpgradeimageEngineer"
		"pin_to_sibling"	"engineer"
		"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"10"
		"wide"			"12"
		"tall"			"12"
		"visible"		"0"
		"enabled"		"1"
		"image"			"mvm/class_upgraded"
		"scaleimage"	"1"
	}
	
	"MvMUpgradeimageMedic"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MvMUpgradeimageMedic"
		"pin_to_sibling"	"medic"
		"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"10"
		"wide"			"12"
		"tall"			"12"
		"visible"		"0"
		"enabled"		"1"
		"image"			"mvm/class_upgraded"
		"scaleimage"	"1"
	}
	
	"MvMUpgradeimageSniper"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MvMUpgradeimageSniper"
		"pin_to_sibling"	"sniper"
		"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"10"
		"wide"			"12"
		"tall"			"12"
		"visible"		"0"
		"enabled"		"1"
		"image"			"mvm/class_upgraded"
		"scaleimage"	"1"
	}
	
	"MvMUpgradeimageSpy"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MvMUpgradeimageSpy"
		"pin_to_sibling"	"spy"
		"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"10"
		"wide"			"12"
		"tall"			"12"
		"visible"		"0"
		"enabled"		"1"
		"image"			"mvm/class_upgraded"
		"scaleimage"	"1"
	}
	
	"MvMUpgradeimageCivilian"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MvMUpgradeimageCivilian"
		"pin_to_sibling"	"civilian"
		"pin_corner_to_sibling" "PIN_BOTTOMRIGHT"
		"pin_to_sibling_corner" "PIN_BOTTOMRIGHT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"10"
		"wide"			"12"
		"tall"			"12"
		"visible"		"0"
		"enabled"		"1"
		"image"			"mvm/class_upgraded"
		"scaleimage"	"1"
	}

	"StartExplanation"
	{
		"controlname"	"CExplanationPopup"
		"fieldname"		"StartExplanation"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"10000"
		"wide"			"250"
		"tall"			"165"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"force_close"	"1"
		"end_x"			"c-170"
		"end_y"			"115"
		"end_wide"		"300"
		"end_tall"		"240"
		"callout_inparents_x"	"c-270"
		"callout_inparents_y"	"40"
		"next_explanation"		"VoucherExplanation"
		
		"TitleLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#TF_MvM_UpgradeExplanation_Title"
			"textAlignment"	"north"
			"xpos"			"20"
			"ypos"			"10"
			"wide"			"260"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_MvM_UpgradeExplanation_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"45"
			"wide"			"260"
			"tall"			"170"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"controlname"	"CEximageButton"
			"fieldname"		"CloseButton"
			"xpos"			"280"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "200 80 60 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"Subimage"
			{
				"controlname"	"ImagePanel"
				"fieldname"		"Subimage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleimage"	"1"
			}				
		}
	}
	
	"TFPlayerModel"
	{
		"controlname"	"CTFPlayerModelPanel"
		"fieldname"		"TFPlayerModel"
		
		"xpos"			"0"
		"ypos"			"60"
		"zpos"			"2"		
		"wide"			"480"
		"tall"			"480"
		
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		
		"render_texture"	"0"
		"fov"			"35"
		"allow_rot"		"1"

		"paintbackground" "1"		
		"paintbackgroundenabled" "1"
		"bgcolor_override" "255 255 255 0"
		
		"model"
		{
			"force_pos"	"1"

			"angles_x" "0"
			"angles_y" "180"
			"angles_z" "0"
			"origin_x" "320"
			"origin_y" "20"
			"origin_z" "-39"
			"frame_origin_x"	"0"
			"frame_origin_y"	"0"
			"frame_origin_z"	"0"
			"spotlight" "1"
		
			"modelname"		""
			"vcd"		"class_select.vcd"
		}
	}
	
	"ClassTipsPanel"
	{
		"controlname"	"CTFClassTipsPanel"
		"fieldname"		"ClassTipsPanel"
		"xpos"			"r260"
		"ypos"			"c-22"
		"zpos"			"7"
		"wide"			"240"
		"tall"			"165"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"bgcolor_override" "0"
		"paintBackgroundType"	"2"
	}
	
	"ClassHighlightPanel"
	{
		"controlname"	"CExplanationPopup"
		"fieldname"		"ClassHighlightPanel"
		"xpos"			"c-75"
		"ypos"			"280"
		"zpos"			"100"
		"wide"			"250"
		"tall"			"170"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"start_x"		"c-238"
		"start_y"		"100"
		"start_wide"	"1"
		"start_tall"	"1"
		"end_x"			"c-325"
		"end_y"			"250"
		"end_wide"		"275"
		"end_tall"		"150"
		"callout_inparents_x"	"c-210"
		"callout_inparents_y"	"437"
		
		"TitleLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#CMenu_ClassHighlightPanel_Title"
			"textAlignment"	"north-west"
			"xpos"			"10"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"ClassHighlightText"
		{
			"controlname"	"CExLabel"
			"fieldname"		"ClassHighlightText"
			"font"			"HudFontSmall"
			"labelText"		"%ClassHighlightText%"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"30"
			"wide"			"210"
			"tall"			"115"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"controlname"	"CEximageButton"
			"fieldname"		"CloseButton"
			"xpos"			"255"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"Subimage"
			{
				"controlname"	"ImagePanel"
				"fieldname"		"Subimage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleimage"	"1"
			}				
		}
	}		
}
