"Resource/UI/EnemyCountPanel.res"
{	
	"EnemyCountPanel"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"EnemyCountPanel"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"3"
		"wide"			"20"
		"tall"			"32"
		"visible"		"0"
		"enabled"		"1"
	}
	
	"EnemyCountimage"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"EnemyCountimage"
		"xpos"			"3"
		"ypos"			"3"
		"zpos"			"3"
		"wide"			"14"
		"tall"			"14"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
	}
	
	"EnemyCountimageBG"
	{
		"controlname"	"Panel"
		"fieldname"		"EnemyCountimageBG"
		"xpos"			"2"
		"ypos"			"2"
		"zpos"			"2"
		"wide"			"16"
		"tall"			"16"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"PaintBackgroundType" "0"
		"bgcolor_override"	"TanLight"
	}
	"EnemyCountimageShadow"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"EnemyCountimageShadow"
		"xpos"			"3"
		"ypos"			"3"
		"zpos"			"0"
		"wide"			"16"
		"tall"			"16"
		"visible"		"1"
		"enabled"		"1"
		"image"			"..\darhud\square\square_shadow"
		"scaleimage"	"1"
	}
	
	"EnemyCountCritimageBG"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"EnemyCountCritimageBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"20"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"PaintBackgroundType" "0"
		//"bgcolor" "Yellow"
		//"bgcolor_override"	"Yellow"
		//"fgcolor_override"	"Yellow"
		//"PaintBackgroundType" "2"
		"image"			"../hud/leaderboard_class_critical"
	}
	
	"EnemyCount"
	{
		"controlname"	"CExLabel"
		"fieldname"		"EnemyCount"
		"font"			"HudFontSmallestBold"
		"fgcolor"		"TanLight"
		"xpos"			"0"
		"ypos"			"18"
		"zpos"			"3"
		"wide"			"20"
		"tall"			"14"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"
		"labelText"		"%enemy_count%"
		"fgcolor_override"	"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
}
