"Resource/UI/hudpvewinpanel.res"
{
	"WinPanelBG"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"WinPanelBG"
		"proportionaltoparent"	"1"
		"xpos"			"16"
		"ypos"			"30"
		"zpos"			"0"
		"wide"			"244"
		"tall"			"50"
		"visible"		"1"
		"bgcolor_override"	"GeneralBackground"
	}

	"WaveCompleteContainer"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"WaveCompleteContainer"
		"proportionaltoparent"	"1"
		"xpos"			"0"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"276"
		"tall"			"30"
		"visible"		"1"
		"PaintBackgroundType" "0"
		
		"Header"
		{
			"controlname"	"ImagePanel"
			"fieldname"	"Header"
			"proportionaltoparent"	"1"
			"xpos"		"0"
			"ypos"		"0"
			"wide"		"276"
			"tall"		"30"
			"image"		"resource/svgs/darhud/scoreboard/scoreboard_middle_mask.svg"
			"drawcolor"	"HUDBlueTeamSolid"
			"scaleimage"	"1"
		}
		"robot1"
		{
			"controlname"	"ImagePanel"
			"fieldname"	"robot1"
			"proportionaltoparent"	"1"
			"xpos"		"14"
			"ypos"		"4"
			"wide"		"22"
			"tall"		"22"
			"image"		"resource/svgs/darhud/mvm/robots.svg"
			"scaleimage"	"1"
			"drawcolor"	"HudShadowSolid"
		}
		"robot2"
		{
			"controlname"	"ImagePanel"
			"fieldname"	"robot2"
			"proportionaltoparent"	"1"
			"xpos"		"r36"
			"ypos"		"4"
			"wide"		"22"
			"tall"		"22"
			"image"		"resource/svgs/darhud/mvm/robots.svg"
			"scaleimage"	"1"
			"drawcolor"	"HudShadowSolid"
		}
		
		"WinningTeamLabel"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"WinningTeamLabel"
			"font"			"HudFontMediumSmallBold"
			"proportionaltoparent"	"1"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"276"
			"tall"			"30"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"#Winpanel_PVE_Evil_Wins"
			"textAlignment"	"center"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}
	}
	
	"WinReasonLabel"
	{	
		"controlname"		"CExLabel"
		"fieldname"		"WinReasonLabel"
		"font"			"HudFontSmall"
		"proportionaltoparent"	"1"
		"xpos"			"16"
		"ypos"			"32"
		"zpos"			"1"
		"wide"			"244"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%WinReasonLabel%"
		"textAlignment"	"center"
		"fgcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}

	"DetailsLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"DetailsLabel"
		"font"			"HudFontSmallest"
		"proportionaltoparent"	"1"
		"xpos"			"20"
		"ypos"			"48"
		"zpos"			"1"
		"wide"			"236"
		"tall"			"30"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%DetailsLabel%"
		"textAlignment"	"center"
		"centerwrap"		"1"
		"fgcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
}