"Resource/UI/StatPanel_PlayTime.res"
{
	"StatPanelBG"
	{
		"controlname"			"EditablePanel"
		"fieldname"			"StatPanelBG"
		"visible"			"0"
	}
	"BG"
	{
		"controlname"			"CTFImagePanel"
		"fieldname"			"BG"
		"proportionaltoparent"	"1"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"1"
		"wide"				"f2"
		"tall"				"f2"
		"visible"			"1"
		"enabled"			"1"
		"image"				"..\darhud\arena\classlayout\arenaclass_neutral"
		"teambg_0"			"..\darhud\arena\classlayout\arenaclass_neutral"
		"teambg_1"			"..\darhud\arena\classlayout\arenaclass_spectator"
		"teambg_2"			"..\darhud\arena\classlayout\arenaclass_red"
		"teambg_3"			"..\darhud\arena\classlayout\arenaclass_blue"
		"teambg_4"			"..\darhud\arena\classlayout\arenaclass_green"
		"teambg_5"			"..\darhud\arena\classlayout\arenaclass_yellow"
		"scaleimage"			"1"
	}
	"BGShadow"
	{
		"controlname"			"ImagePanel"
		"fieldname"			"BGShadow"
		"proportionaltoparent"	"1"
		"pin_to_sibling"		"BG"
		"xpos"				"-2"
		"ypos"				"-2"
		"zpos"				"0"
		"wide"				"f2"
		"tall"				"f2"
		"visible"			"1"
		"enabled"			"1"
		"image"				"resource/svgs/darhud/arena/arenaclass_mask.svg"
		"drawcolor"			"HudShadow"
		"scaleimage"			"1"
	}
	"StatPanelClassimage"
	{
		"controlname"		"ImagePanel"
		"fieldname"		"StatPanelClassimage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"0"
		"tall"			"0"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/class_scoutred"
		"scaleimage"		"1"
	}
	"titleLabel"
	{	
		"controlname"			"Label"
		"fieldname"			"titleLabel"
		"font"				"HudFontSmallest"
		"proportionaltoparent"	"1"
		"xpos"				"8"
		"ypos"				"2"
		"zpos"				"2"
		"wide"				"f18"
		"tall"				"10"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"%title%"
		"textAlignment"		"west"
		"fgcolor_override"	"GeneralLabel"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"summaryLabel"
	{	
		"controlname"			"Label"
		"fieldname"			"summaryLabel"
		"proportionaltoparent"	"1"
		"font"				"HudFontTiny"
		"xpos"				"8"
		"ypos"				"12"
		"zpos"				"2"
		"wide"				"f18"
		"tall"				"30"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"%statdesc%"
		"textAlignment"		"north-west"
		"wrap"				"1"
		"fgcolor_override"	"GeneralLabel"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"StatBox"
	{
		"controlname"			"ImagePanel"
		"fieldname"			"StatBox"
		"proportionaltoparent"	"1"
		"xpos"				"8"
		"ypos"				"31"
		"zpos"				"2"
		"wide"				"f18"
		"tall"				"21"
		"visible"			"1"
		"enabled"			"1"
		"image"				"resource/svgs/darhud/arena/arenaclass_mask_reverse.svg"
		"drawcolor"			"HudShadow"
		"scaleimage"			"1"
	}
	"StatLabelLarge"
	{	
		"controlname"			"Label"
		"fieldname"			"StatLabelLarge"
		"proportionaltoparent"	"1"
		"pin_to_sibling"		"StatBox"
		"font"				"HudFontMediumSmallBold"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"3"
		"wide"				"f18"
		"tall"				"20"
		"visible"			"1"
		"enabled"			"1"
		"textinsetx"			"10"
		"labelText"			"%stattextlarge%"
		"textAlignment"		"west"
		"fgcolor_override"	"GeneralLabel"
		"dropshadow"			"1"
		"dropshadowoffset"	"3"
	}
	"StatLabelSmall"
	{	
		"controlname"			"Label"
		"fieldname"			"StatLabelSmall"
		"proportionaltoparent"	"1"
		"pin_to_sibling"		"StatBox"
		"font"				"HudFontSmallest"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"3"
		"wide"				"f18"
		"tall"				"20"
		"visible"			"1"
		"enabled"			"1"
		"textinsetx"			"10"
		"labelText"			"%stattextsmall%"
		"textAlignment"		"west"
		"fgcolor_override"	"GeneralLabel"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
}
