"Resource/UI/winpanel.res"
{
	"TFStatsSummary"
	{
		"controlname"	"EditablePanel"
		"fieldname"	"TFStatsSummary"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"f0"
		"tall"		"480"
		"visible"	"0"
		"enabled"	"1"
		"bgcolor_override"	"0 0 0 0"
	}
	
	"StatData"
	{
		"controlname"		"EditablePanel"
		"fieldname"			"StatData"
		"xpos"				"cs-0.5"
		"ypos"				"-130"
		"zpos"				"1"
		"wide"				"f0"
		"tall"				"480"
		"visible"			"1"
		"enabled"			"1"

		"InteractiveHeaders"	
		{
			"controlname"	"EditablePanel"
			"fieldname"		"InteractiveHeaders"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"f0"
			"tall"			"480"
			"visible"		"1"
			"enabled"		"1"

			"BarChartComboA"
			{
				"controlname"		"ComboBox"
				"fieldname"			"BarChartComboA"
				"font"				"TargetDataFont"
				"xpos"				"c-285"
				"ypos"				"212"
				"zpos"				"10"
				"wide"				"154"
				"tall"				"14"
				"autoResize"		"0"
				"pinCorner"			"0"
				"visible"			"1"
				"enabled"			"1"
				"tabPosition"		"1"
				"textHidden"		"0"
				"editable"			"0"
				"maxchars"			"-1"
				"NumericInputOnly"	"0"
				"unicode"			"0"
				
				"fgcolor_override"			"TanLight"
				"selectionColor_override"	"Blank"

			}
			"BarChartComboA_BG"
			{
				"controlname"			"ImagePanel"
				"fieldname"				"BarChartComboA_BG"
				"xpos"					"0"
				"ypos"					"0"
				"zpos"					"2"
				"wide"					"154"
				"tall"					"14"
				"visible"				"1"
				"enabled"				"1"
				"fillcolor"				"TanDarker"
				"PaintBackgroundType"	"0"
				
				"pin_to_sibling"		"BarChartComboA"
			}
			"BarChartComboB"
			{
				"controlname"		"ComboBox"
				"fieldname"			"BarChartComboB"
				"font"				"TargetDataFont"
				"xpos"				"c-127"
				"ypos"				"212"
				"zpos"				"10"
				"wide"				"154"
				"tall"				"14"
				"autoResize"		"0"
				"pinCorner"			"0"
				"visible"			"1"
				"enabled"			"1"
				"tabPosition"		"1"
				"textHidden"		"0"
				"editable"			"0"
				"maxchars"			"-1"
				"NumericInputOnly"	"0"
				"unicode"			"0"
				
				"fgcolor_override"			"TanLight"
				"selectionColor_override"	"Blank"

			}
			"BarChartComboB_BG"
			{
				"controlname"			"ImagePanel"
				"fieldname"				"BarChartComboB_BG"
				"xpos"					"0"
				"ypos"					"0"
				"zpos"					"2"
				"wide"					"154"
				"tall"					"14"
				"visible"				"1"
				"enabled"				"1"
				"fillcolor"				"TanDarker"
				"PaintBackgroundType"	"0"
				
				"pin_to_sibling"		"BarChartComboB"
			}
			"ClassCombo"
			{
				"controlname"		"ComboBox"
				"fieldname"			"ClassCombo"
				"font"				"TargetDataFont"
				"xpos"				"c+120"
				"ypos"				"212"
				"zpos"				"10"
				"wide"				"167"
				"tall"				"14"
				"autoResize"		"0"
				"pinCorner"			"0"
				"visible"			"1"
				"enabled"			"1"
				"tabPosition"		"1"
				"textHidden"		"0"
				"editable"			"0"
				"maxchars"			"-1"
				"NumericInputOnly"	"0"
				"unicode"			"0"
				
				"fgcolor_override"			"TanLight"
				"selectionColor_override"	"Blank"
			}
			"ClassCombo_BG"
			{
				"controlname"			"ImagePanel"
				"fieldname"				"ClassCombo_BG"
				"xpos"					"0"
				"ypos"					"0"
				"zpos"					"2"
				"wide"					"167"
				"tall"					"14"
				"visible"				"1"
				"enabled"				"1"
				"fillcolor"				"TanDarker"
				"PaintBackgroundType"	"0"
				
				"pin_to_sibling"		"ClassCombo"
			}
		}
		"ClassBarBG1A"
		{
			"controlname"			"ImagePanel"
			"fieldname"				"ClassBarBG1A"
			"xpos"					"c-285"
			"ypos"					"230"
			"zpos"					"2"
			"wide"					"312"
			"tall"					"16"
			"visible"				"1"
			"enabled"				"1"
			"fillcolor"				"TanDarker"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarBG1B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG1B"
			"xpos"			"c+29"
			"ypos"			"230"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBar1A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar1A"
			"xpos"			"c-282"
			"ypos"			"232"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"162 148 135 255"
			"PaintBackgroundType"	"0"
		}
		"ClassBar1B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar1B"
			"xpos"			"c-127"
			"ypos"			"232"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"162 148 135 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarLabel1A"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel1A"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel1A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"228"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel1B"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel1B"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel1B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"228"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel1"
		{
			"controlname"		"Label"
			"fieldname"		"ClassLabel1"
			"font"			"HudFontSmallestBold"
			"labelText"		"%class1%"
			"textAlignment"		"west"
			"xpos"			"c+35"
			"ypos"			"228"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarBG2A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG2A"
			"xpos"			"c-285"
			"ypos"			"248"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBarBG2B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG2B"
			"xpos"			"c+29"
			"ypos"			"248"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBar2A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar2A"
			"xpos"			"c-282"
			"ypos"			"250"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"93 60 27 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBar2B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar2B"
			"xpos"			"c-127"
			"ypos"			"250"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"93 60 27 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarLabel2A"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel2A"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel2A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"246"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel2B"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel2B"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel2B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"246"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel2"
		{
			"controlname"		"Label"
			"fieldname"		"ClassLabel2"
			"font"			"HudFontSmallestBold"
			"labelText"		"%class2%"
			"textAlignment"		"west"
			"xpos"			"c+35"
			"ypos"			"246"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarBG3A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG3A"
			"xpos"			"c-285"
			"ypos"			"266"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBarBG3B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG3B"
			"xpos"			"c+29"
			"ypos"			"266"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBar3A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar3A"
			"xpos"			"c-282"
			"ypos"			"268"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"134 93 39 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBar3B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar3B"
			"xpos"			"c-127"
			"ypos"			"268"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"134 93 39 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarLabel3A"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel3A"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel3A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"264"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel3B"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel3B"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel3B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"264"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel3"
		{
			"controlname"		"Label"
			"fieldname"		"ClassLabel3"
			"font"			"HudFontSmallestBold"
			"labelText"		"%class3%"
			"textAlignment"		"west"
			"xpos"			"c+35"
			"ypos"			"264"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarBG4A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG4A"
			"xpos"			"c-285"
			"ypos"			"284"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBarBG4B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG4B"
			"xpos"			"c+29"
			"ypos"			"284"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBar4A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar4A"
			"xpos"			"c-282"
			"ypos"			"286"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"207 147 95 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBar4B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar4B"
			"xpos"			"c-127"
			"ypos"			"286"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"207 147 95 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarLabel4A"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel4A"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel4A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"282"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel4B"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel4B"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel4B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"282"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel4"
		{
			"controlname"		"Label"
			"fieldname"		"ClassLabel4"
			"font"			"HudFontSmallestBold"
			"labelText"		"%class4%"
			"textAlignment"		"west"
			"xpos"			"c+35"
			"ypos"			"282"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarBG5A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG5A"
			"xpos"			"c-285"
			"ypos"			"302"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBarBG5B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG5B"
			"xpos"			"c+29"
			"ypos"			"302"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBar5A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar5A"
			"xpos"			"c-282"
			"ypos"			"304"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"226 184 146 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBar5B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar5B"
			"xpos"			"c-127"
			"ypos"			"304"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"226 184 146 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarLabel5A"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel5A"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel5A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"300"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel5B"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel5B"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel5B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"300"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel5"
		{
			"controlname"		"Label"
			"fieldname"		"ClassLabel5"
			"font"			"HudFontSmallestBold"
			"labelText"		"%class5%"
			"textAlignment"		"west"
			"xpos"			"c+35"
			"ypos"			"300"
			"zpos"			"5"
			"wide"			"282"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarBG6A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG6A"
			"xpos"			"c-285"
			"ypos"			"320"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBarBG6B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG6B"
			"xpos"			"c+29"
			"ypos"			"320"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBar6A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar6A"
			"xpos"			"c-282"
			"ypos"			"322"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"162 148 135 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBar6B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar6B"
			"xpos"			"c-127"
			"ypos"			"322"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"162 148 135 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarLabel6A"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel6A"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel6A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"318"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel6B"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel6B"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel6B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"318"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel6"
		{
			"controlname"		"Label"
			"fieldname"		"ClassLabel6"
			"font"			"HudFontSmallestBold"
			"labelText"		"%class6%"
			"textAlignment"		"west"
			"xpos"			"c+35"
			"ypos"			"318"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarBG7A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG7A"
			"xpos"			"c-285"
			"ypos"			"338"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBarBG7B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG7B"
			"xpos"			"c+29"
			"ypos"			"338"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBar7A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar7A"
			"xpos"			"c-282"
			"ypos"			"340"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"93 60 27 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBar7B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar7B"
			"xpos"			"c-127"
			"ypos"			"340"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"93 60 27 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarLabel7A"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel7A"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel7A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"336"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel7B"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel7B"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel7B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"336"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel7"
		{
			"controlname"		"Label"
			"fieldname"		"ClassLabel7"
			"font"			"HudFontSmallestBold"
			"labelText"		"%class7%"
			"textAlignment"		"west"
			"xpos"			"c+35"
			"ypos"			"336"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}		
		"ClassBarBG8A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG8A"
			"xpos"			"c-285"
			"ypos"			"356"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBarBG8B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG8B"
			"xpos"			"c+29"
			"ypos"			"356"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBar8A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar8A"
			"xpos"			"c-282"
			"ypos"			"358"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"134 93 39 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBar8B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar8B"
			"xpos"			"c-127"
			"ypos"			"358"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"134 93 39 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarLabel8A"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel8A"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel8A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"354"

			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel8B"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel8B"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel8B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"354"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel8"
		{
			"controlname"		"Label"
			"fieldname"		"ClassLabel8"
			"font"			"HudFontSmallestBold"
			"labelText"		"%class8%"
			"textAlignment"		"west"
			"xpos"			"c+35"
			"ypos"			"354"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}		
		"ClassBarBG9A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG9A"
			"xpos"			"c-285"
			"ypos"			"374"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBarBG9B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG9B"
			"xpos"			"c+29"
			"ypos"			"374"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBar9A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar9A"
			"xpos"			"c-282"
			"ypos"			"376"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"207 147 95 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBar9B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar9B"
			"xpos"			"c-127"
			"ypos"			"376"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"207 147 95 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarLabel9A"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel9A"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel9A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"372"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel9B"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel9B"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel9B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"372"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel9"
		{
			"controlname"		"Label"
			"fieldname"		"ClassLabel9"
			"font"			"HudFontSmallestBold"
			"labelText"		"%class9%"
			"textAlignment"	"west"
			"xpos"			"c+35"
			"ypos"			"372"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}
		"ClassBarBG10A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG10A"
			"xpos"			"c-285"
			"ypos"			"406"
			"zpos"			"2"
			"wide"			"312"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBarBG10B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBarBG10B"
			"xpos"			"c+29"
			"ypos"			"406"
			"zpos"			"2"
			"wide"			"70"
			"tall"			"16"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"ClassBar10A"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar10A"
			"xpos"			"c-282"
			"ypos"			"408"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"226 184 146 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBar10B"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"ClassBar10B"
			"xpos"			"c-127"
			"ypos"			"408"
			"zpos"			"3"
			"wide"			"151"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"226 184 146 255"
			"PaintBackgroundType"	"0"
		}	
		"ClassBarLabel10A"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel10A"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel10A%"
			"textAlignment"		"west"
			"xpos"			"c-282"
			"ypos"			"404"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassBarLabel10B"
		{
			"controlname"		"Label"
			"fieldname"		"ClassBarLabel10B"
			"font"			"TargetDataFont"
			"labelText"		"%classbarlabel10B%"
			"textAlignment"		"west"
			"xpos"			"c-127"
			"ypos"			"404"
			"zpos"			"6"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}				
		"ClassLabel10"
		{
			"controlname"		"Label"
			"fieldname"		"ClassLabel10"
			"font"			"HudFontSmallestBold"
			"labelText"		"%class10%"
			"textAlignment"	"west"
			"xpos"			"c+35"
			"ypos"			"404"
			"zpos"			"5"
			"wide"			"300"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
		}						
		"RecordsSubBG1"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"RecordsSubBG1"
			"xpos"			"c+120"
			"ypos"			"230"
			"zpos"			"2"
			"wide"			"167"
			"tall"			"170"
			"visible"		"1"
			"enabled"		"1"
			"fillcolor"		"TanDarker"
			"PaintBackgroundType"	"0"
		}
		"OverallRecord1Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord1Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord1label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"235"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord1Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord1Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord1value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"235"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord2Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord2Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord2label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"245"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord2Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord2Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord2value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"245"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord3Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord3Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord3label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"255"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord3Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord3Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord3value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"255"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord4Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord4Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord4label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"265"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord4Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord4Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord4value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"265"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord5Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord5Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord5label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"275"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord5Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord5Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord5value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"275"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord6Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord6Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord6label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"285"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord6Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord6Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord6value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"285"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord7Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord7Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord7label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"295"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord7Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord7Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord7value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"295"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord8Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord8Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord8label%"
			"textAlignment"	"west"
			"xpos"			"c+128"
			"ypos"			"305"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord8Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord8Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord8value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"305"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord9Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord9Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord9label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"315"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord9Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord9Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord9value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"315"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord10Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord10Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord10label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"325"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord10Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord10Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord10value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"325"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord11Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord11Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord11label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"335"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord11Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord11Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord11value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"335"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord12Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord12Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord12label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"345"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord12Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord12Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord12value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"345"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord13Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord13Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord13label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"355"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord13Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord13Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord13value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"355"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord14Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord14Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord14label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"365"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord14Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord14Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord14value%"
			"textAlignment"	"west"
			"xpos"			"c+210"
			"ypos"			"365"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord15Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord15Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord15label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"375"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord15Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord15Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord15value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"375"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}
		"OverallRecord16Label"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord16Label"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord16label%"
			"textAlignment"		"west"
			"xpos"			"c+128"
			"ypos"			"385"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}							
		"OverallRecord16Value"
		{
			"controlname"		"Label"
			"fieldname"		"OverallRecord16Value"
			"font"			"TargetDataFont"
			"labelText"		"%classrecord16value%"
			"textAlignment"		"west"
			"xpos"			"c+210"
			"ypos"			"385"
			"zpos"			"5"
			"wide"			"200"
			"tall"			"10"
			"visible"		"1"
			"enabled"		"1"
		}
	}
	
	"Tipimage"
	{
		"controlname"			"CTFImagePanel"
		"fieldname"				"Tipimage"
		"xpos"					"-5"
		"ypos"					"0"
		"zpos"					"12"
		"wide"					"30"
		"tall"					"30"
		"visible"				"0"
		"enabled"				"1"
		"scaleimage"			"1"
		
		"pin_to_sibling"			"NextTipButton"
		"pin_corner_to_sibling"		"PIN_CENTER_LEFT"
		"pin_to_sibling_corner"		"PIN_CENTER_LEFT"
	}
	
	"TipText"
	{
		"controlname"			"Label"
		"fieldname"				"TipText"
		"labelText"				"%tiptext%"
		"textAlignment"			"west"
		"xpos"					"5"
		"ypos"					"0"
		"zpos"					"12"
		"wide"					"200"
		"tall"					"60"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"1"
		"wrap"					"1"
		"font"					"HudFontSmallest"
		
		"pin_to_sibling"		"Tipimage"
		"pin_corner_to_sibling"	"PIN_CENTER_LEFT"
		"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
	}
	
	"NextTipButton"
	{
		"controlname"				"CExButton"
		"fieldname"					"NextTipButton"
		"xpos"						"cs-0.5"
		"ypos"						"316"
		"zpos"						"13"
		"wide"						"240"
		"tall"						"40"
		"visible"					"1"
		"enabled"					"1"
		"labelText"					""
		"tooltiptext"				"#TF_NextTip"
		"Command"					"nexttip"
		"paintbackgroundtype"		"4"
		"paintbackground"			"0"
		"roundedcorners"			"0"
		
		"defaultbgColor_override"	"0 0 0 0"
		"armedbgColor_override"		"0 0 0 0"
		"depressedbgColor_override"	"0 0 0 0"

		"sound_released"			"UI/buttonclick.wav"
		"button_activation_type"	"1"
	}

	"TooltipPanel"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"TooltipPanel"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"10000"
		"wide"			"150"
		"tall"			"50"
		"visible"		"0"
		"border"			"DarHudTooltip"

		"TipLabel"
		{
			"controlname"			"CExLabel"
			"fieldname"			"TipLabel"
			"font"				"HudFontSmallest"
			"labelText"			"%tiptext%"
			"textAlignment"		"center"
			"xpos"				"10"
			"ypos"				"5"
			"zpos"				"2"
			"wide"				"140"
			"tall"				"30"
			"autoResize"			"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"fgcolor_override"	"GeneralLabel"
			"auto_wide_tocontents" "1"
			"dropshadow"			"1"
			"dropshadowoffset"	"2"
		}
	}
}
