"Resource/UI/TrainingComplete.res"
{
 	"TrainingComplete"
	{
		"controlname"		"CTFTrainingComplete"
		"fieldname"			"TrainingComplete"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"0"
		"wide"				"f0"
		"tall"				"480"
		"visible"			"1"
		"enabled"			"1"
  
		"Next"
		{
			"controlname"		"CExButton"
			"fieldname"		"Next"
			"xpos"			"r190"
			"ypos"			"r40"
			"zpos"			"6"
			"wide"			"150"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"#Button_NextTraining"
			"textAlignment"		"center"
			"command"		"next"
			"font"			"HudFontSmallBold"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"roundedcorners"	"0"
			
			"sound_armed"		"ui/buttonrollover.wav"
			"sound_depressed"	"ui/buttonclick.wav"
			"sound_released"	"ui/buttonclickrelease.wav"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}

		"Quit"
		{
			"controlname"		"CExButton"
			"fieldname"		"Quit"
			"xpos"			"r190"
			"ypos"			"r40"
			"zpos"			"6"
			"wide"			"150"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"labelText"		"#Button_QuitTraining"
			"textAlignment"		"center"
			"command"		"quit"
			"font"			"HudFontSmallBold"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"roundedcorners"	"0"
			
			"sound_armed"		"ui/buttonrollover.wav"
			"sound_depressed"	"ui/buttonclick.wav"
			"sound_released"	"ui/buttonclickrelease.wav"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}	
		
		"Replay"
		{
			"controlname"	"CExButton"
			"fieldname"		"Replay"
			"xpos"			"40"
			"ypos"			"r40"
			"zpos"			"6"
			"wide"			"150"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"#Button_ReplayTraining"
			"textAlignment"	"center"
			"command"		"replay"
			"font"			"HudFontSmallBold"
			"fgcolor"		"Black"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"roundedcorners"	"0"
			
			"sound_armed"		"ui/buttonrollover.wav"
			"sound_depressed"	"ui/buttonclick.wav"
			"sound_released"	"ui/buttonclickrelease.wav"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}
		
		"BottomBar"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"BottomBar"
			"xpos"			"0"
			"ypos"			"r50"
			"zpos"			"5"
			"wide"			"f0"
			"tall"			"50"
			"proportionaltoparent"	"1"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"	
			"fillcolor"		"LoadoutFooter"
			"PaintBackgroundType"	"0"
		}
		"FooterLine"
		{
			"controlname"	"EditablePanel"
			"fieldname"		"FooterLine"
			"pin_to_sibling"	"BottomBar"
			"pin_corner_to_sibling"	"pin_topleft"
			"pin_to_sibling_corner"	"pin_topleft"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"6"
			"wide"			"f0"
			"tall"			"2"
			"proportionaltoparent"	"1"
			"visible"		"1"
			"enabled"		"1"
			"bgcolor_override"	"ButtonMM"
			"scaleimage"	"1"
		}

		"TopBar"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"TopBar"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"5"
			"wide"			"f0"
			"tall"			"50"
			"visible"		"1"
			"enabled"		"1"
			"image"			"../darhud/mainmenu/striped_pattern"
			"drawcolor"		"BackgroundDefault"
			"tileimage"		"1"
			"PaintBackgroundType"	"0"
		}
		"HeaderLine"
		{
			"controlname"	"EditablePanel"
			"fieldname"		"HeaderLine"
			"pin_to_sibling"	"TopBar"
			"pin_corner_to_sibling"	"pin_bottomleft"
			"pin_to_sibling_corner"	"pin_bottomleft"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"6"
			"wide"			"f0"
			"tall"			"2"
			"proportionaltoparent"	"1"
			"visible"		"1"
			"enabled"		"1"
			"bgcolor_override"	"ButtonMM"
			"scaleimage"	"1"
		}
	}

	"imageBomb"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"imageBomb"
		"xpos"			"c-64"
		"ypos"			"135"
		"zpos"			"2"
		"wide"			"128"
		"tall"			"128"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/graduation_bomb"
		"scaleimage"	"1"
	}

	"Results"
	{
		"controlname"	"EditablePanel"
		"fieldname"	"Results"
		"xpos"		"c-200"
		"ypos"		"105"
		"zpos"		"1"
		"wide"		"400"
		"tall"		"480"
		"visible"	"1"
		"enabled"	"1"

		"ResultsLabel"
		{
			"controlname"		"Label"
			"fieldname"		"ResultsLabel"
		  	"font"			"HudFontMediumSmallBold"
			"labelText"		"%wintext%"
			"textAlignment"		"center"
			"xpos"			"0"
			"ypos"			"10"
			"zpos"			"1"
			"wide"			"400"
			"tall"			"20"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}
		"ResultsBG"
		{
			"controlname"	"EditablePanel"
			"fieldname"		"ResultsBG"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"400"
			"tall"			"275"
			"visible"		"1"
			"PaintBackgroundType"	"2"
			"border"		"NoBorder"
			"bgcolor_override"	"LoadoutTooltip"
		}
		"ResultsText"
		{
			"controlname"		"CExRichText"
			"fieldname"		"ResultsText"
			"xpos"			"15"
			"ypos"			"150"
			"zpos"			"2"
			"wide"			"370"
			"tall"			"215"
			"autoResize"		"3"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"		"0"
			"maxchars"		"-1"
			"text"			""
			"wrap"			"1"
			"textAlignment"		"north-west"
			"font"			"HudFontSmall"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
	}			
}