"resource/ui/vsh_hud.res"
{	
	"ObjectiveStatusRobotDestruction"
	{
		"controlname"		"EditablePanel"
		"fieldname"			"ObjectiveStatusRobotDestruction"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"1"
		"wide"				"f0"
		"tall"				"480"
		"visible"			"1"
		"enabled"			"1"

		"left_steal_edge_offset"	"97"
		"right_steal_edge_offset"	"97"
		"robot_x_offset"		"78"
		"robot_y_offset"		"47"
		"robot_x_step"			"23"
		"robot_y_step"			"0"
		

		"color_blue"			"84 111 127 255"
		"color_red"				"171 59 59 255"

		"if_hybrid"
		{
			"zpos"			"-1"
		}

		"robot_kv"
		{
			"controlname"	"CTFHudRobotDestruction_RobotIndicator"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"20"
			"tall"			"20"
			"visible"		"1"
			"bgcolor_override"		"0 0 0 0"
			"PaintBackgroundType"	"0"
			"paintborder"	"0"
			"AutoResize" "0"
			"skip_autoresize" "1"
		}
	}

	"alivecounter"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"alivecounter"
		"xpos"			"c-32"
		"ypos"			"r80"
		"zpos"			"-10"
		"wide"			"60"
		"tall"			"35"
		"visible"		"1"
	
		"background"
		{
			"controlname"	"CTFImagePanel"
			"fieldname"		"background"
			"xpos"			"5"
			"ypos"			"7"
			"zpos"			"0"
			"wide"			"50"
			"tall"			"25"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"image"			"..\darhud\counter\counter_red"
		}
		
		"backgroundshadow"
		{
			"controlname"	"CTFImagePanel"
			"fieldname"		"backgroundshadow"
			"xpos"			"6"
			"ypos"			"8"
			"zpos"			"-1"
			"wide"			"50"
			"tall"			"25"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"image"			"..\darhud\counter\counter_shadow"
		}

		"playerimage"
		{
			"controlname"	"ImagePanel"		
			"fieldname"		"playerimage"
			"xpos"			"12"
			"ypos"			"11"
			"zpos"			"3"
			"wide"			"8"
			"tall"			"15"
			"visible"		"1"
			"enabled"		"1"
			"image"			"capture_icon_white"
			"scaleimage"	"1"
		}
	}
	
	"damagecounter"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"damagecounter"
		"xpos"			"c-32"
		"ypos"			"r112"
		"zpos"			"-10"
		"wide"			"60"
		"tall"			"35"
		"visible"		"1"
	
		"background"
		{
			"controlname"	"CTFImagePanel"
			"fieldname"		"background"
			"xpos"			"3"
			"ypos"			"7"
			"zpos"			"0"
			"wide"			"55"
			"tall"			"25"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"image"			"..\darhud\counter\counter_shadow"
		}	
		"dmg_icon"
		{
			"controlname"	"ImagePanel"		
			"fieldname"		"playerimage"
			"xpos"			"7"
			"ypos"			"11"
			"zpos"			"3"
			"wide"			"15"
			"tall"			"15"
			"visible"		"1"
			"enabled"		"1"
			"image"			"vssaxtonhale/dmg_icon"
			"scaleimage"	"1"
		}
	}
	
	"ScoreContainer"
	{
		"fieldname"				"ScoreContainer"
		"controlname"			"EditablePanel"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"0"
		"wide"					"f0"
		"tall"					"f0"
		"scaleimage"			"0"
		"visible"				"1"
		"enabled"				"1"

		"Borderimage1"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Borderimage1"	
			"xpos"			"c-100"
			"ypos"			"68"
			"zpos"			"2"
			"wide"			"200"
			"tall"			"25"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"image"			"../darhud/boss_bar/vsh/boss_bar_surround"
			"scaleimage"	"1"			
		}
		"Borderimage2"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Borderimage2"
			"pin_to_sibling"	"Borderimage1"
			"xpos"			"-2"
			"ypos"			"-2"
			"zpos"			"0"
			"wide"			"200"
			"tall"			"25"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"image"			"../darhud/boss_bar/boss_bar_surround_shadow"
			"scaleimage"	"1"			
		}
		"Borderimage3"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"Borderimage3"
			"pin_to_sibling"	"Borderimage1"
			"pin_corner_to_sibling"	"PIN_TOPRIGHT"
			"pin_to_sibling_corner"	"PIN_TOPRIGHT"
			"xpos"			"29"
			"ypos"			"18"
			"zpos"			"4"
			"wide"			"76"
			"tall"			"38"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"image"			"../darhud/boss_bar/vsh/hale_hat"
			"scaleimage"	"1"			
		}
		
		"ProgressBarContainer"
		{
			"fieldname"				"ProgressBarContainer"
			"controlname"			"EditablePanel"
			"xpos"					"cs-0.5"
			"ypos"					"72"
			"zpos"					"1"
			"wide"					"184"
			"tall"					"17"
			"visible"				"1"
			"enabled"				"1"
			"proportionaltoparent"	"1"
					
			"BlueProgressBarFill"
			{
				"controlname"	"EditablePanel"
				"fieldname"		"BlueProgressBarFill"
				"proportionaltoparent"	"1"
				"xpos"			"cs-0.5"
				"ypos"			"0"
				"zpos"			"5"
				"wide"			"234"
				"tall"			"17"
				"autoResize"	"1"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"tabPosition"	"0"
				"scaleimage"	"0"	
				"image"			"vssaxtonhale/boss_bar"
			}
		}
		
		"BlueScoreValueContainer"
		{
			"controlname"		"EditablePanel"
			"fieldname"			"BlueScoreValueContainer"
			"xpos"				"c-100"
			"ypos"				"70"
			"zpos"				"20"
			"wide"				"200"
			"tall"				"100"
			"visible"			"1"
			"enabled"			"1"
			"bgcolor_override"		"0 0 0 0"
			"proportionaltoparent"	"1"

			"Score"
			{
				"controlname"	"CExLabel"
				"fieldname"		"Score"
				"xpos"			"c-100"
				"ypos"			"0"
				"zpos"			"28"
				"wide"			"200"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
				"textAlignment"	"center"	
				"labelText"		"%score%"
				"font"			"HudFontMediumSmallBold"
				"fgcolor"		"ObjectiveLabel"		
				"proportionaltoparent"	"1"
			}	
		
			"ScoreShadow"
			{
				"controlname"	"CExLabel"
				"fieldname"		"ScoreShadow"
				"xpos"			"c-99"
				"ypos"			"1"
				"zpos"			"27"
				"wide"			"200"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
				"textAlignment"	"center"	
				"labelText"		"%score%"
				"font"			"HudFontMediumSmallBold"
				"fgcolor"		"ObjectiveShadow"
				"proportionaltoparent"	"1"
			}
		}
		
		"RedScoreValueContainer"
		{
			"controlname"		"EditablePanel"
			"fieldname"			"RedScoreValueContainer"
			"xpos"				"cs-0.5"
			"ypos"				"r71"
			"zpos"				"20"
			"wide"				"200"
			"tall"				"100"
			"visible"			"1"
			"enabled"			"1"
			"bgcolor_override"		"0 0 0 0"
			"proportionaltoparent"	"1"

			"Score"
			{
				"controlname"	"CExLabel"
				"fieldname"		"Score"
				"font"			"HudFontMediumSmallBold"
				"xpos"			"c-12"
				"ypos"			"0"
				"zpos"			"28"
				"wide"			"30"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
				"textAlignment"	"center"	
				"labelText"		"%score%"
				"font"			"CenterPrintText"
				"fgcolor"		"ObjectiveLabel"		
				"proportionaltoparent"	"1"
			}	
		
			"ScoreShadow"
			{
				"controlname"	"CExLabel"
				"fieldname"		"ScoreShadow"
				"font"			"HudFontMediumSmallBold"
				"xpos"			"c-11"
				"ypos"			"1"
				"zpos"			"27"
				"wide"			"30"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
				"textAlignment"	"center"	
				"labelText"		"%score%"
				"font"			"CenterPrintText"
				"fgcolor"		"ObjectiveShadow"
				"proportionaltoparent"	"1"
			}
		}
	}
}