"Resource/UI/WaveCompletePanel.res"
{
	"Background"
	{
		"controlname"		"ScalableImagePanel"
		"fieldname"		"Background"
		"proportionaltoparent"	"1"
		"xpos"			"16"
		"ypos"			"30"
		"zpos"			"0"
		"wide"			"244"
		"tall"			"50"
		"visible"		"0"
		"image"		"..\darhud\square\square_white"
		"drawcolor"	"GeneralBackground"
		"alpha"		"192"
	}
	"Background2"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"Background2"
		"proportionaltoparent"	"1"
		"xpos"			"16"
		"ypos"			"30"
		"zpos"			"0"
		"wide"			"244"
		"tall"			"50"
		"visible"		"1"
		"bgcolor_override"	"GeneralBackground"
	}
	
	"WaveCompleteContainer"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"WaveCompleteContainer"
		"proportionaltoparent"	"1"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"276"
		"tall"			"30"
		"visible"		"1"
		"PaintBackgroundType" "2"
		
		"Header"
		{
			"controlname"	"ImagePanel"
			"fieldname"	"Header"
			"proportionaltoparent"	"1"
			"xpos"		"0"
			"ypos"		"0"
			"wide"		"276"
			"tall"		"30"
			"image"		"resource/svgs/darhud/scoreboard/scoreboard_middle_mask.svg"
			"drawcolor"	"HudRedTeamSolid"
			"scaleimage"	"1"
		}
		
		"WaveCompleteLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"WaveCompleteLabel"
			"font"			"HudFontMediumSmallBold"
			"textAlignment"	"center"
			"labelText"		"%titletext%"
			"proportionaltoparent"	"1"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"276"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}
	}
		
	"CreditContainer"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"CreditContainer"
		"pin_to_sibling"	"Background2"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"150"
		"tall"			"50"
		"visible"		"1"
		
		"CreditCollectedTextLabel"
		{
			"controlname"		"CExLabel"
			"fieldname"		"CreditCollectedTextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Collected"
			"textAlignment"	"west"
			"xpos"			"10"
			"ypos"			"8"
			"zpos"			"1"
			"wide"			"105"
			"tall"			"12"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"CreditCollectedCountLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"CreditCollectedCountLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditscollected%"
			"textAlignment" "east"
			"xpos"			"80"
			"ypos"			"8"
			"zpos"			"1"
			"wide"			"65"
			"tall"			"12"
			"fgcolor"		"CreditsGreen"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"CreditMissedTextLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"CreditMissedTextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Missed"
			"textAlignment" "west"
			"xpos"			"10"
			"ypos"			"20"
			"zpos"			"1"
			"wide"			"105"
			"tall"			"12"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"CreditMissedCountLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"CreditMissedCountLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditsmissed%"
			"textAlignment" "east"
			"xpos"			"80"
			"ypos"			"20"
			"zpos"			"1"
			"wide"			"65"
			"tall"			"12"
			"fgcolor"		"RedSolid"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"CreditBonusTextLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"CreditBonusTextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Bonus"
			"textAlignment" "west"
			"xpos"			"10"
			"ypos"			"32"
			"zpos"			"1"
			"wide"			"105"
			"tall"			"12"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"CreditBonusCountLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"CreditBonusCountLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditbonus%"
			"textAlignment" "east"
			"xpos"			"80"
			"ypos"			"32"
			"zpos"			"1"
			"wide"			"65"
			"tall"			"12"
			"fgcolor"		"CreditsGreen"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
	}
	
	"VerticalDivider"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"VerticalDivider"
		"pin_to_sibling"	"CreditContainer"
		"pin_corner_to_sibling"	"pin_center_left"
		"pin_to_sibling_corner"	"pin_center_right"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"40"
		"bgcolor_override"	"HudRedTeamSolid"
	}
	
	"RatingContainer"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"RatingContainer"
		"pin_to_sibling"	"VerticalDivider"
		"pin_corner_to_sibling"	"pin_center_left"
		"pin_to_sibling_corner"	"pin_center_right"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"94"
		"tall"			"50"
		"visible"		"1"
		
		"RatingLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"RatingLabel"
			"font"			"HudFontSmall"
			"labelText"		"%ratinglabel%"
			"textAlignment" "center"
			"proportionaltoparent"	"1"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"f0"
			"tall"			"20"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"RatingTextBackground"
		{
			"controlname"	"ImagePanel"
			"fieldname"	"RatingTextBackground"
			"proportionaltoparent"	"1"
			"xpos"		"c-15"
			"ypos"		"16"
			"wide"		"30"
			"tall"		"30"
			"zpos"		"0"
			"image"		"resource/svgs/darhud/star13_mask.svg"
			"drawcolor"	"HudRedTeamSolid"
			"scaleimage"	"1"
		}
		"RatingText"
		{
			"controlname"	"CExLabel"
			"fieldname"		"RatingText"
			"font"			"HudFontMediumBold"
			"labelText"		"%ratingscore%"
			"textAlignment" "center"
			"proportionaltoparent"	"1"
			"xpos"			"c-60"
			"ypos"			"16"
			"zpos"			"2"
			"wide"			"120"
			"tall"			"30"
			"fgcolor"		"White"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}
	}
	
	"RespecBackground"
	{
		"controlname"	"ScalableImagePanel"
		"fieldname"		"RespecBackground"
		"proportionaltoparent"	"1"
		"xpos"			"16"
		"ypos"			"81"
		"wide"			"244"
		"tall"			"20"
		"visible"		"0"
		"enabled"		"1"
		"image"			"..\darhud\square\square_white"
		"drawcolor"		"GeneralBackground"
		"alpha"			"222"
	}

	"RespecContainer"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"RespecContainer"
		"proportionaltoparent"	"1"
		"xpos"			"16"
		"ypos"			"81"
		"wide"			"244"
		"tall"			"20"
		"visible"		"1"
		"PaintBackgroundType" "2"
	
		"RespecTextLabelWin"
		{
			"controlname"	"CExLabel"
			"fieldname"		"RespecTextLabelWin"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Respecs"
			"textAlignment" "west"
			"xpos"			"5"
			"ypos"			"0"
			"wide"			"150"
			"tall"			"20"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"RespecCountLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"RespecCountLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%respeccount%"
			"textAlignment" "east"
			"textinsetx"		"1"
			"proportionaltoparent"	"1"
			"xpos"			"r34"
			"ypos"			"0"
			"zpos"			"1"
			"wide"			"30"
			"tall"			"20"
			"fgcolor"		"CreditsGreen"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
	}
}
