"Resource/UI/main_menu/LoadoutMenu_ItemSelector.res"
{
	"ItemSelectionPanel"
	{
		"controlname"					"EditablePanel"
		"fieldname"					"ItemSelectionPanel"
		
		"xpos"						"0"
		"ypos"						"82"
		"zpos"						"4"
		
		"wide"						"f0"
		"tall"						"338"
		
		"settitlebarvisible"			"0"
		
		"bgcolor_override"			"LoadoutBackground"
		
		"item_ypos"					"60"
		"item_ydelta"					"80"
		
		"item_backpack_offcenter_x"	"-288"
		"item_backpack_xdelta"			"4"
		"item_backpack_ydelta"			"3"
		
		"visible"					"1"

		"modelpanels_selection_kv"
		{
			"wide"			"576"
			"tall"			"64"
			
			"model_xpos"		"2"
			"model_wide"		"100"
			"model_tall"		"70"
			"model_center_x"	"0"
			
			"text_ypos"		"0"
			"text_forcesize"	"1"
			"text_center"		"1"
			"text_yoffset"	"2"
			
			"inset_eq_x"		"519"
			"inset_eq_y"		"50"

			"deferred_description"	"1"
			"deferred_icon"		"1"
		}
		"modelpanels_kv"
		{
			"controlname"			"CItemModelPanel"
			"xpos"				"c-70"
			"ypos"				"270"
			"wide"				"54"
			"tall"				"42"
			"bgcolor_override"	"0 0 0 0"
			"noitem_textcolor"	"117 107 94 255"
			"PaintBackgroundType"	"2"
			"paintborder"			"1"
			
			"model_xpos"	"2"
			"model_ypos"	"0" 
			"model_wide"	"100"
			"model_tall"	"70"
			"text_ypos"		"60"
			"text_center"	"1"
			"name_only"		"1"
			
			"use_item_sounds"	"1"
			"use_item_sounds_alt"	"1"
			
			"inset_eq_x"	"4"
			"inset_eq_y"	"2"

			"deferred_description"	"1"
			
			"visible"			"0"
			
			"itemmodelpanel"
			{
				"use_item_rendertarget" "0"
				"allow_rot"				"0"
			}
		}
		"duplicatelabels_kv"
		{
			"font"			"ItemFontNameSmallest"
			"textAlignment"	"center"
			"wide"			"20"
			"tall"			"15"
			"zpos"			"1"
			"enabled"		"1"
			"fgcolor"		"153 204 255 255"
		}
	}

	"NameFilterLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"NameFilterLabel"
		"font"			"HudFontSmallestBold"
		"labelText"		"#Store_NameFilterLabel"
		"textAlignment"	"west"
		"xpos"			"c+205"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"20"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"fgcolor"		"StoreDarkTan"
	}

	"NameFilterTextEntry"
	{
		"controlname"		"TextEntry"
		"fieldname"		"NameFilterTextEntry"
		"xpos"		"c+205"
		"ypos"		"15"
		"zpos"		"2"
		"wide"		"90"
		"tall"		"19"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"1"
		"unicode"		"1"
		"fgcolor_override"	"117 107 94 255"
		"bgcolor_override"	"251 235 202 255"
		"paintbackgroundtype" "2"
		"font"		"HudFontSmallest"
	}

	"LeftCaratLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"			"LeftCaratLabel"
		"font"				"HudFontSmallestBold"
		"labelText"			">>"
		"textAlignment"		"west"
		"xpos"				"c-290"
		"ypos"				"22"
		"zpos"				"1"
		"wide"				"20"
		"tall"				"15"
		"autoResize"		"1"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"fgcolor_override"	"200 80 60 255"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"ClassLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"			"ClassLabel"
		"xpos"				"c-275"
		"ypos"				"13"
		"zpos"				"6"
		"wide"				"500"
		"tall"				"30"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"%loadoutclass%"
		"textAlignment"		"west"
		"font"				"HudFontBiggerBold"
		"fgcolor"			"MainMenuLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
		"mouseinputenabled"	"0"
	}
	"TopLine"
	{
		"controlname"		"ImagePanel"
		"fieldname"			"TopLine"
		"proportionaltoparent"	"1"
		"xpos"				"c-275"
		"ypos"				"43"
		"zpos"				"2"
		"wide"				"199"
		"tall"				"10"
		"visible"			"1"
		"enabled"			"1"
		"image"				"loadout_dotted_line"
		"tileimage"			"1"
		"drawcolor"			"132 121 107 255"
		"tileVertically"	"0"
	}
	
	"BottomLine"
	{
		"controlname"		"ImagePanel"
		"fieldname"			"BottomLine"
		"proportionaltoparent"	"1"
		"xpos"				"cs-0.5"
		"ypos"				"270"
		"zpos"				"2"
		"wide"				"512"
		"tall"				"10"
		"visible"			"1"
		"enabled"			"1"
		"image"				"loadout_dotted_line"
		"tileimage"			"1"
		"drawcolor"			"132 121 107 255"
		"tileVertically"	"0"
	}
		
	"TopLine2"
	{
		"controlname"		"ImagePanel"
		"fieldname"			"TopLine2"
		"proportionaltoparent"	"1"
		"xpos"				"c76"
		"ypos"				"43"
		"zpos"				"2"
		"wide"				"199"
		"tall"				"10"
		"visible"			"1"
		"enabled"			"1"
		"image"				"loadout_dotted_line"
		"tileimage"			"1"
		"drawcolor"			"132 121 107 255"
		"tileVertically"	"0"
	}
	"ItemSlotLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"ItemSlotLabel"
		"font"			"HudFontMediumBold"
		"labelText"		"#PrimaryWeapon"
		"textAlignment"	"east"
		"fgcolor"			"MainMenuLabel"
		"xpos"			"c-100"
		"ypos"			"20"
		"zpos"			"1"
		"wide"			"375"
		"tall"			"25"
		"visible"		"1"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
		"textinsetx"	"2"
	}

	"NoItemsLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"NoItemsLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#NoItemsToEquip"
		"textAlignment"	"center"
		"xpos"			"c-300"
		"ypos"			"120"
		"zpos"			"10"
		"wide"			"600"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"fgcolor_override" "200 80 60 255"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}
	
	"CancelButton"
	{
		"controlname"	"CExButton"
		"fieldname"		"CancelButton"
		"xpos"			"c-200"
		"ypos"			"400"
		"zpos"			"2"
		"wide"			"200"
		"tall"			"25"
		"visible"		"0"
		"enabled"		"0"
		"labelText"		"#Cancel"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"Command"		"vguicancel"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	
	"BackButton"
	{
		"controlname"		"CEximageButton"
		"fieldname"		"BackButton"
		"style"			"CommandButton"
		"xpos"			"c-50"
		"ypos"			"292"
		"wide"			"100"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Loadout_Back"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"default"		"0"
		"Command"		"back"
		
		"dropshadowoffset"	"3"
	}
	"BackButtonShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"BackButtonShadow"
		"style"			"MainMenuButtonShadow"
		"pin_to_sibling"	"BackButton"
		
		"wide"			"100"
		"tall"			"25"
	}
	
	"OnlyAllowUniqueQuality"
	{
		"controlname"	"CheckButton"
		"fieldname"		"OnlyAllowUniqueQuality"
		"labelText"		"#OnlyAllowUniqueQuality"
		"Font"			"HudFontSmallestBold"
		"textAlignment"	"east"
		"xpos"			"c-306"
		"ypos"			"340"
		"zpos"			"1"
		"wide"			"290"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"dulltext"		"0"
		"brighttext"	"0"
	}	
	
	"ShowBackpack"
	{
		"controlname"	"CExButton"
		"fieldname"		"ShowBackpack"
		"xpos"			"c100"
		"ypos"			"340"
		"zpos"			"20"
		"wide"			"200"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Selection_ShowBackpack"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"textinsetx"	"50"
		"dulltext"		"0"
		"brighttext"	"0"
		"Command"		"show_backpack"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	"ShowSelection"
	{
		"controlname"	"CExButton"
		"fieldname"		"ShowSelection"
		"xpos"			"c100"
		"ypos"			"340"
		"zpos"			"20"
		"wide"			"200"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#Selection_ShowSelection"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"textinsetx"	"50"
		"dulltext"		"0"
		"brighttext"	"0"
		"Command"		"show_selection"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
	}
	
	"HamburgerButton"
	{
		"controlname"		"CEximageButton"
		"fieldname"		"HamburgerButton"
		"style"			"MainMenuButton"
		"xpos"			"c-285"
		"ypos"			"308"
		"zpos"			"1"
		"wide"			"20"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"actionsignallevel"	"2"
		"Command"		"tf2c_loadout_grid 0"
		"tooltiptext"		"#dar_loadout_list"
		
		"image_default"	"resource/svgs/mainmenu/icon_hamburger.svg"
		"stayselectedonclick"	"1"
		"image_selectedcolor"	"ButtonArmedLabelMM"
		"border_selected"		"DarhudMMSquareButtonArmed"
		
		"dropshadowoffset"	"3"
		"Subimage"
		{
			"wide"		"f8"
			"tall"		"o1"
			"xpos"		"cs-0.5+1"
		}
	}
	"HamburgerButtonShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"HamburgerButtonShadow"
		"style"			"MainMenuButtonShadow"
		"wide"			"20"
		"tall"			"20"
		"pin_to_sibling"	"HamburgerButton"
	}
	"BentoButton"
	{
		"controlname"		"CEximageButton"
		"fieldname"		"BentoButton"
		"style"			"MainMenuButton"
		"xpos"			"c-260"
		"ypos"			"308"
		"zpos"			"1"
		"wide"			"20"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"actionsignallevel"	"2"
		"Command"		"tf2c_loadout_grid 1"
		"tooltiptext"		"#dar_loadout_grid"
		
		"image_default"	"resource/svgs/mainmenu/icon_bento.svg"
		"stayselectedonclick"	"1"
		"image_selectedcolor"	"ButtonArmedLabelMM"
		"border_selected"		"DarhudMMSquareButtonArmed"
		
		"dropshadowoffset"	"3"
		"Subimage"
		{
			"wide"		"f8"
			"tall"		"o1"
			"xpos"		"cs-0.5+1"
		}
	}
	"BentoButtonShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"BentoButtonShadow"
		"style"			"MainMenuButtonShadow"
		"wide"			"20"
		"tall"			"20"
		"pin_to_sibling"	"BentoButton"
	}
	
	"PrevPageButton"
	{
		"controlname"		"CEximageButton"
		"fieldname"		"PrevPageButton"
		"style"			"CommandButton"
		"xpos"			"c195"
		"ypos"			"308"
		"wide"			"20"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"<"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"Command"		"prevpage"
		
		"dropshadowoffset"	"3"
	}
	"PrevPageButtonShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"PrevPageButtonShadow"
		"style"			"MainMenuButtonShadow"
		"wide"			"20"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		
		"pin_to_sibling"	"PrevPageButton"
	}
	
	"CurPageLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CurPageLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%backpackpage%"
		"textAlignment"	"center"
		"xpos"			"c220"
		"ypos"			"308"
		"zpos"			"1"
		"wide"			"40"
		"tall"			"20"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override" "200 80 60 255"
		
		"dropshadowoffset"	"3"
	}
	
	"NextPageButton"
	{
		"controlname"		"CEximageButton"
		"fieldname"		"NextPageButton"
		"style"			"CommandButton"
		"xpos"			"c265"
		"ypos"			"308"
		"wide"			"20"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		">"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"Command"		"nextpage"
		
		"dropshadowoffset"	"3"
	}
	"NextPageButtonShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"NextPageButtonShadow"
		"style"			"MainMenuButtonShadow"
		"wide"			"20"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		
		"pin_to_sibling"	"NextPageButton"
	}
	
	"mouseoveritempanel"
	{
		"controlname"	"CItemModelPanel"
		"fieldname"		"mouseoveritempanel"
		"xpos"			"c-70"
		"ypos"			"270"
		"zpos"			"100"
		"wide"			"300"
		"tall"			"300"
		"visible"		"0"
		"bgcolor_override"		"0 0 0 0"
		"noitem_textcolor"		"117 107 94 255"
		"PaintBackgroundType"	"2"
		"paintborder"	"1"
		
		"text_ypos"			"20"
		"text_center"		"1"
		"model_hide"		"1"
		"resize_to_text"	"1"
		"padding_height"	"15"
		
		"attriblabel"
		{
			"font"			"ItemFontAttribLarge"
			"xpos"			"0"
			"ypos"			"30"
			"zpos"			"2"
			"wide"			"140"
			"tall"			"60"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%attriblist%"
			"textAlignment"	"center"
			"fgcolor"		"117 107 94 255"
			"centerwrap"	"1"
		}
	}
}


