"Resource/UI/main_menu/LoadingScreen.res"
{
	"LoadingBackground"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"LoadingBackground"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"f0"
		"visible"		"1"
		"enabled"		"1"
	}
	
	"MainBackground"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MainBackground"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"
		"enabled"		"1"
		"image"			""
		"scaleimage"	"1"
	}
	
    "Classimage"
    {
        "controlname"	"ImagePanel"
        "fieldname"		"Classimage"
        "xpos"			"cs-0.5"
        "ypos"			"rs1-40"
        "wide"			"900"
        "tall"			"o0.5"
        "visible"		"1"
        "enabled"		"1"
        "image"			""
        "scaleimage"	"1"
    }
	
	"LoadingShadedBar"
	{
		"controlname"			"ImagePanel"
		"fieldname"				"LoadingShadedBar"
		"xpos"					"0"
		"ypos"					"r75"
		"zpos"					"5"
		"wide"					"f0"
		"tall"					"80"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"fillcolor"				"Black"
		"PaintBackgroundType"	"0"
	}
	
	"MapInfoShadedBar"
	{
		"controlname"			"ImagePanel"
		"fieldname"				"MapInfoShadedBar"
		"xpos"					"0"
		"ypos"					"r100"
		"zpos"					"5"
		"wide"					"f0"
		"tall"					"0"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"fillcolor"				"Black"
		"PaintBackgroundType"	"0"
	}
	
	"MapLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"MapLabel"
		"font"			"LoadingMapFont"
		"labelText"		"%maplabel%"
		"textAlignment"	"west"
		"xpos"			"c-305"
		"ypos"			"r65"
		"zpos"			"6"
		"wide"			"295"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}
	
	"MapTypeLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"MapTypeLabel"
		"font"			"LoadingGametypeFont"
		"labelText"		"%maptype%"
		"textAlignment"	"west"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"6"
		"wide"			"350"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
		
		"pin_to_sibling"		"MapLabel"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
	}
	
	"PlayTimeLabel"
	{
		"controlname"		"Label"
		"fieldname"			"PlayTimeLabel"
		"font"				"TF2CMenuTitle"
		"labelText"			"#StatSummary_StatTitle_TotalPlaytime"
		"textAlignment"		"west"
		"xpos"				"-475"
		"ypos"				"-138"
		"zpos"				"6"
		"wide"				"300"
		"tall"				"18"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"fgcolor_override"	"HUDBlack"
		
		"pin_to_sibling"		"Classimage"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"
	}
	
	"PlayTime"
	{
		"controlname"	"CExLabel"
		"fieldname"		"PlayTime"
		"font"			"TF2CPlaytime"
		"labelText"		"%playtime%"
		"textAlignment"	"west"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"6"
		"wide"			"300"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor"		"HUDBlack"
		
		"pin_to_sibling"		"PlayTimeLabel"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
	}
	
	"TipLabel"
	{
		"controlname"		"Label"
		"fieldname"			"TipLabel"
		"font"				"TF2CMenuTitle"
		"labelText"			"#StatSummary_Label_TIP"
		"textAlignment"		"west"
		"xpos"				"-12"
		"ypos"				"20"
		"zpos"				"6"
		"wide"				"190"
		"tall"				"18"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"fgcolor_override"	"HUDBlack"
		
		"pin_to_sibling"		"PlayTime"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
	}
	
	"TipText"
	{
		"controlname"		"Label"
		"fieldname"			"TipText"
		"font"				"HudFontSmallest"
		"labelText"			"%tiptext%"
		"textAlignment"		"north-west"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"6"
		"wide"				"240"
		"tall"				"100"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"wrap"				"1"
		"fgcolor_override"	"HUDBlack"
		
		"pin_to_sibling"		"TipLabel"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_BOTTOMLEFT"
	}
}
