"Resource/training/offlinepractice/mapselection.res"
{
	"MapImagePanel"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MapImagePanel"
		"xpos"			"60"
		"ypos"			"5"
		"zpos"			"0"
		"wide"			"330"
		"tall"			"330"
		"visible"		"1"
		"tileimage"		"0"
		"scaleimage"	"1"
		"border"		"ButtonBorder"
		"paintbackgroundtype"	"2"
		"paintbackground"	"1"
	}
	"MapimageBorder"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"MapimageBorder"
		"xpos"			"56"
		"ypos"			"0"
		"wide"			"339"
		"tall"			"195"
		"border"			"OuterShadowBorder"
		"visible"		"1"
	}

	"HackCoverBottomOfMapImagePanel"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"MapImagePanel"
		"xpos"		"60"
		"ypos"		"320"
		"wide"		"330"
		"tall"		"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"bgcolor_override"	"40 37 37 255"
	}
	
	"GradientPanel"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"GradientPanel"
		"xpos"			"60"
		"ypos"			"107"
		"zpos"			"1"
		"wide"			"330"
		"tall"			"80"
		"visible"		"0"
		"tileimage"		"0"
		"scaleimage"	"1"
		"image"			"training/gradient_black"
	}
	
	"PrevButton"
	{
		"controlname"	"CExButton"
		"fieldname"		"PrevButton"
		"xpos"			"36"
		"ypos"			"76"
		"zpos"			"20"
		"wide"			"18"
		"tall"			"44"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_LessThan"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"roundedcorners"	"0"
		"Command"		"goprev"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}	
	
	"NextButton"
	{
		"controlname"	"CExButton"
		"fieldname"		"NextButton"
		"xpos"			"396"
		"ypos"			"76"
		"zpos"			"20"
		"wide"			"18"
		"tall"			"44"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_GreaterThan"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"roundedcorners"	"0"
		"Command"		"gonext"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}	
	
	"MapNameLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"MapNameLabel"
		"font"			"HudFontMediumBold"
		"labelText"		"%mapname%"
		"textAlignment"	"center"
		"xpos"			"60"
		"ypos"			"142"
		"zpos"			"3"
		"wide"			"330"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"fgcolor_override"	"246 237 211 255"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}
	
	"MapSubtitleLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"MapNameLabel"
		"font"			"HudFontSmall"
		"labelText"		"%mapsubtitle%"
		"textAlignment"	"center"
		"xpos"			"60"
		"ypos"			"162"
		"zpos"			"3"
		"wide"			"330"
		"tall"			"40"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"fgcolor_override"	"246 237 211 255"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	
	"CurPageLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CurPageLabel"
		"font"			"HudFontMediumSmallBold"
		"labelText"		"%curpage%"
		"textAlignment"	"north"
		"center"		"1"
		"xpos"			"63"
		"ypos"			"8"
		"zpos"			"100"
		"wide"			"33"
		"tall"			"18"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"fgcolor_override"	"GeneralLabel"
		"border"		"NoBorder"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}
	
	"StartOfflinePracticeButton"
	{
		"controlname"		"CExButton"
		"fieldname"			"StartOfflinePracticeButton"
		"xpos"				"150"
		"ypos"				"260"
		"zpos"				"1"
		"wide"				"150"
		"tall"				"30"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"#TF_StartPractice"
		"font"				"HudFontSmallBold"
		"textAlignment"		"center"
		"textinsetx"		"50"
		"dulltext"			"0"
		"brighttext"		"0"
		"Command"			"startofflinepractice"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"paintbackground"	"0"
			
		"border_default"		"DarhudMMSquareButton"
		"border_armed"		"DarhudMMSquareButtonArmed"
		"border_selected"		"DarhudMMSquareButtonDepressed"
		"border_depressed"	"DarhudMMSquareButtonDepressed"
		"border_disabled"		"DarhudMMSquareButtonDisabled"
			
		"defaultFgColor_override"		"ButtonLabelMM"
		"armedFgColor_override"		"ButtonArmedLabelMM"
		"selectedFgColor_override"		"ButtonDepressedLabelMM"
		"depressedFgColor_override"	"ButtonDepressedLabelMM"
		"disabledFgColor_override"		"ButtonDisabledLabelMM"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}
	"StartOfflinePracticeButtonShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"			"StartOfflinePracticeButtonShadow"
		"style"				"MainMenuButtonShadow"
		"pin_to_sibling"		"StartOfflinePracticeButton"
		"xpos"				"-2"
		"ypos"				"-2"
		"wide"				"150"
		"tall"				"30"
	}
	
	"SettingsBG"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"SettingsBG"
		"xpos"		"60"
		"ypos"		"195"
		"zpos"		"0"
		"wide"		"330"
		"tall"		"40"
		"bgcolor_override"	"ListingBody"
		"visible"	"1"
	}
	
	"DifficultyLabel"
	{
		"controlname"			"CExLabel"
		"fieldname"			"DifficultyLabel"
		"font"				"SubmenuText"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
		"labelText"			"#TF_Bot_Difficulty"
		"textAlignment"		"east"
		"xpos"				"0"
		"ypos"				"196"
		"zpos"				"2"
		"zpos"				"1"
		"wide"				"190"
		"tall"				"18"
		"visible"			"1"
		"enabled"			"1"
		"wrap"				"0"
		"fgcolor_override"	"246 237 211 255"
	}
	
	"DifficultyComboBox"
	{
		"controlname"		"ComboBox"
		"fieldname"			"DifficultyComboBox"
		"Font"				"SubmenuTextEntry"
		"xpos"				"200"
		"ypos"				"196"
		"zpos"				"2"
		"wide"				"100"
		"tall"				"18"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"			"0"
		"maxchars"			"-1"
		"NumericInputOnly"	"0"
		"unicode"			"0"
		"textinsetx"		"50"
		
		"FgColor_override"	"MainText"
		"bgcolor_override"		"0 0 0 255"
		
		"disabledFgColor_override" "235 226 202 255"
		"disabledBgColor_override" "51 47 46 255"
		"selectionColor_override" "51 47 46 255"
		"selectionTextColor_override" "235 226 202 255"
		"defaultSelectionBG2Color_override" "51 47 46 255"
	}
	
	"PlayersLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"PlayersLabel"
		"font"			"SubmenuText"
		"labelText"		"#IT_BotAddition_Title"
		"textAlignment"	"east"
		"xpos"			"0"
		"ypos"			"216"
		"zpos"			"2"
		"wide"			"190"
		"tall"			"18"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"fgcolor_override"	"246 237 211 255"
	}
	
	"NumPlayersTextEntry"
	{
		"controlname"	"TextEntry"
		"fieldname"		"NumPlayersTextEntry"
		"font"			"SubmenuTextEntry"
		"textHidden"	"0"
		"textAlignment"	"west"
		"unicode"		"1"
		"wrap"			"0"
		"xpos"			"200"
		"ypos"			"216"
		"zpos"			"50"
		"wide"			"22"
		"tall"			"18"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"maxchars"		"2"
		"NumericInputOnly"	"1"
		"selectallonfirstfocus"	"1"
		"roundedcorners"		"0"
		
		"bgcolor_override"	"16 14 14 255"
		"fgcolor_override"	"246 237 211 255"
	}
	
	"SuggestedPlayerCountLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"SuggestedPlayerCountLabel"
		"font"			"HudFontSmallest"
		"labelText"		""
		"textAlignment"	"west"
		"xpos"			"230"
		"ypos"			"216"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"18"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"fgcolor_override"	"116 105 92 255"
	}
}
