"Resource/training/offlinepractice/practicemodeselection.res"
{
	"GameModeImagePanel"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"GameModeImagePanel"
		"xpos"			"60"
		"ypos"			"15"
		"zpos"			"1"
		"wide"			"250"
		"tall"			"250"
		"visible"		"1"
		"tileimage"		"0"
		"scaleimage"	"1"
		"border"		"ButtonBorder"
		"paintbackgroundtype"	"0"
		"paintbackground"	"1"
	}
	
	"GameModeimageBgPanel"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"GameModeimageBgPanel"
		"xpos"			"60"
		"ypos"			"5"
		"zpos"			"1"
		"wide"			"330"
		"tall"			"255"
		"visible"		"1"
		"tileimage"		"0"
		"scaleimage"		"1"
		"image"			"../darhud/invisible"
		"fillcolor"		"252 241 216 255"
	}
	"GameModeimageBorder"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"GameModeimageBorder"
		"xpos"			"55"
		"ypos"			"0"
		"wide"			"340"
		"tall"			"265"
		"border"			"OuterShadowBorder"
		"visible"		"1"
	}
	
	"PrevButton"
	{
		"controlname"	"CExButton"
		"fieldname"		"PrevButton"
		"xpos"			"36"
		"ypos"			"105"
		"zpos"			"20"
		"wide"			"18"
		"tall"			"43"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_LessThan"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"roundedcorners"	"0"
		"Command"		"goprev"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}	
	
	"NextButton"
	{
		"controlname"	"CExButton"
		"fieldname"		"NextButton"
		"xpos"			"396"
		"ypos"			"105"
		"zpos"			"20"
		"wide"			"18"
		"tall"			"43"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_GreaterThan"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"roundedcorners"	"0"
		"Command"		"gonext"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}	
	
	"GameModeLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"GameModeLabel"
		"font"			"HudFontMediumSmallBold"
		"labelText"		"%gamemode%"
		"textAlignment"	"center"
		"xpos"			"60"
		"ypos"			"10"
		"zpos"			"2"
		"wide"			"330"
		"tall"			"20"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"fgcolor_override"	"83 75 66 255"
	}
	
	"CurPageLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CurPageLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%curpage%"
		"textAlignment"	"north"
		"xpos"			"70"
		"ypos"			"10"
		"zpos"			"2"
		"wide"			"40"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"1"
		"fgcolor_override"	"83 75 66 255"
	}
	
	"DescLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"DescLabel"
		"font"			"HudFontSmallest"
		"labelText"		"%description%"
		"textAlignment"	"center"
		"xpos"			"60"
		"ypos"			"230"
		"zpos"			"2"
		"wide"			"330"
		"tall"			"20"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"fgcolor_override"	"83 75 66 255"
	}
	
	"SelectCurrentGameModeButton"
	{
		"controlname"		"CExButton"
		"fieldname"			"SelectCurrentGameModeButton"
		"xpos"				"160"
		"ypos"				"270"
		"zpos"				"1"
		"wide"				"130"
		"tall"				"30"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"labelText"			"#TF_Select"
		"font"				"HudFontSmallBold"
		"textAlignment"		"center"
		"textinsetx"		"50"
		"dulltext"			"0"
		"brighttext"		"0"
		"Command"			"selectcurrentgamemode"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
			
		"border_default"		"DarhudMMSquareButton"
		"border_armed"		"DarhudMMSquareButtonArmed"
		"border_selected"		"DarhudMMSquareButtonDepressed"
		"border_depressed"	"DarhudMMSquareButtonDepressed"
		"border_disabled"		"DarhudMMSquareButtonDisabled"
			
		"defaultFgColor_override"		"ButtonLabelMM"
		"armedFgColor_override"		"ButtonArmedLabelMM"
		"selectedFgColor_override"		"ButtonDepressedLabelMM"
		"depressedFgColor_override"	"ButtonDepressedLabelMM"
		"disabledFgColor_override"		"ButtonDisabledLabelMM"
		
		"paintbackground"	"0"
		
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}
	"SelectCurrentGameModeButtonShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"			"SelectCurrentGameModeShadow"
		"style"				"MainMenuButtonShadow"
		"pin_to_sibling"		"SelectCurrentGameModeButton"
		"xpos"				"-2"
		"ypos"				"-2"
		"wide"				"130"
		"tall"				"30"
	}
}