"Resource/UI/build_menu/base_already_built.res"
{
	"ItemNameLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"ItemNameLabel"
		"font"			"MeterLabelFont"
		"fgcolor"		"White"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"52"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Object_Sentry"
		"textAlignment"	"center"
		"dropshadow"		"1"
		"dropshadowoffset"	"1"
	}
	
	"ItemBackground"	
	{
		"controlname"	"EditablePanel"
		"fieldname"		"ItemBackground"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"52"
		"tall"			"52"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"bgcolor_override"		"15 15 15 255"
		"paintbackgroundtype" "2"
		"proportionaltoparent"	"1"
		"roundedcorners"	"0"
	}	
	
	"DestroyIcon"	
	{
		"controlname"	"ImagePanel"
		"fieldname"		"DestroyIcon"
		"pin_to_sibling" "ItemNameLabel"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"3"
		"zpos"			"1"
		"wide"			"34"
		"tall"			"34"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"image"			"resource/svgs/engineer/ico_demolish.svg"
		"drawcolor"		"162 60 60 255"
	}
		
	"BuildingIcon"	
	{
		"controlname"	"ImagePanel"
		"fieldname"		"BuildingIcon"
		"pin_to_sibling" "ItemNameLabel"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"3"
		"zpos"			"2"
		"wide"			"34"
		"tall"			"34"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		// "icon"			"obj_status_sentrygun_1"
		"drawcolor"		"White"
	}
}