"Resource/UI/disguise_menu/scout_blue.res"
{
	"ItemNameLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"ItemName"
		"font"			"Default"
		"xpos"			"0"
		"ypos"			"10"
		"zpos"			"1"
		"wide"			"45"
		"tall"			"20"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Class_Name_Scout"
		"textAlignment"	"Center"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	
	"ClassIcon"	
	{
		"visible"		"0"
		"enabled"		"0"
	}	
	
	"Icon"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"Icon"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"25"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		//"image"			"../hud/leaderboard_class_scout"
		"bgcolor_override"	"HUDRedTeam"
		"scaleimage"	"0"		
	}		
    
    "bg"
    {
        "controlname"		"panel"
		"fieldname"		"bg"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"25"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"		"1"
		//"fillcolor"			"0 0 0 192"
		"proportionaltoparent"	"1"
    }
		
	"NumberBg"	
	{
		"controlname"	"CIconPanel"
		"fieldname"		"NumberBg"
		"pin_to_sibling" "Icon"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"3"
		"zpos"			"0"
		"wide"			"11"
		"tall"			"11"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"icon"			"ico_key_blank"
		"iconColor"		"255 255 255 255"
	}	
	
	"NewNumberLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"NumberLabel"
		"font"			"FontStorePrice"
		"fgcolor"		"Black"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"11"
		"tall"			"11"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"1"
		"textAlignment"	"Center"
		"dulltext"		"1"
		"brighttext"	"0"
		"pin_to_sibling" "NumberBg"
	}
	
	"NumberLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"NumberLabel"
		"font"			"FontStorePrice"
		"fgcolor"		"Black"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"11"
		"tall"			"11"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"1"
		"textAlignment"	"Center"
		"dulltext"		"1"
		"brighttext"	"0"
		"pin_to_sibling" "NumberBg"
	}
}