"Resource/UI/ConfirmDialog.res"
{
	"ConfirmDialog"
	{
		"fieldname"				"ConfirmDialog"
		"visible"				"1"
		"enabled"				"1"
		"xpos"					"c-150"
		"ypos"					"c-200"
		"wide"					"300"
		"tall"					"240"
		"bgcolor_override"		"DialogBackground"
		"paintbackgroundtype"	"0"
		"settitlebarvisible"	"0"
        "paintBorder"   "1"
	}
	
	"TitleLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"TitleLabel"
		"font"			"HudFontMediumBold"
		"labelText"		"#ConfirmTitle"
        "fgcolor"   "MainMenuLabel"
		"textAlignment"	"north"
		"xpos"			"0"
		"ypos"			"10"
		"zpos"			"1"
		"wide"			"300"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}
	
	"ExplanationLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"ExplanationLabel"
		"font"			"HudFontSmall"
		"labelText"		"%text%"
		"textAlignment"	"center"
		"xpos"			"40"
		"ypos"			"40"
		"zpos"			"1"
		"wide"			"220"
		"tall"			"130"
		"visible"		"1"
		"enabled"		"1"
		"centerwrap"	"1"
		"fgcolor_override" "200 80 60 255"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
		
	"CancelButton"
	{
		"controlname"	"CExButton"
		"fieldname"		"CancelButton"
		"xpos"			"190"
		"ypos"			"185"
		"zpos"			"20"
		"wide"			"100"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cancel"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"Command"		"cancel"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"roundedcorners"	"0"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}

	"ConfirmButton"
	{
		"controlname"	"CExButton"
		"fieldname"		"ConfirmButton"
		"xpos"			"10"
		"ypos"			"185"
		"zpos"			"20"
		"wide"			"175"
		"tall"			"25"
		"default"		"1"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#ConfirmButtonText"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"Command"		"confirm"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"roundedcorners"	"0"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}			
}
