"Resource/UI/build_menu/base_selectable.res"
{
	"MainBackground"	
	{
		"controlname"	"CIconPanel"
		"fieldname"		"MainBackground"
		"xpos"			"3"
		"ypos"			"1"
		"zpos"			"0"
		"wide"			"98"
		"tall"			"135"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"icon"			"hud_menu_item_bg"
		"iconColor"		"128 128 128 255"
	}
	
	"ItemNameLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"MeterLabelFont"
		"font"			"Default"
		"xpos"			"10"
		"ypos"			"2"
		"zpos"			"1"
		"wide"			"84"
		"tall"			"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Empty_Slot"
		"labelText_lodef"		"#TF_Empty_Slot"
		"textAlignment"	"Left"
		"dropshadow"		"1"
		"dropshadowoffset"	"1"
		"fgcolor"		"black"
	}

	"ItemBackground"
	{
		"controlname"	"CIconPanel"
		"fieldname"		"ItemBackground"
		"xpos"			"4"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"98"
		"tall"			"135"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"icon"			"hud_menu_item_bg"
		"iconColor"		"ProgressOffWhite"
		"roundedcorners"	"0"
	}
	
	"BuildingIcon"	
	{
		"controlname"	"CIconPanel"
		"fieldname"		"BuildingIcon"
		"xpos"			"22"
		"ypos"			"19"
		"zpos"			"2"
		"wide"			"56"
		"tall"			"56"
		"visible"		"0"
		"enabled"		"1"
		"scaleimage"	"1"
		"icon"			"hud_menu_sentry_build"
		"iconColor"		"255 255 255 255"
	}
	
	"MetalIcon"	
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MetalIcon"
		"pin_to_sibling" "BuildingIcon"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_BOTTOMLEFT"
		"xpos"			"3"
		"ypos"			"-2"
		"zpos"			"1"
		"wide"			"16"
		"tall"			"16"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"image"			"resource/svgs/engineer/ico_metal.svg"
		"drawcolor"		"TanDarker"
	}
	
	"CostLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"CostLabel"
		"font"			"HudFontSmall"
		"fgcolor"		"TanDarker"
		"xpos"			"23"
		"ypos"			"78"
		"zpos"			"1"
		"wide"			"84"
		"tall"			"13"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"Left"
		"dropshadow"		"1"
		"dropshadowoffset"	"1"
	}
}