"Resource/UI/build_menu/base_already_built.res"
{
	"ItemNameLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"ItemNameLabel"
		"font"			"MeterLabelFont"
		"fgcolor"		"HudBlack"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"62"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Object_Sentry"
		"textAlignment"	"center"
		"dropshadow"		"1"
		"dropshadowoffset"	"1"
	}
	
	"ItemBackground"	
	{
		"controlname"	"EditablePanel"
		"fieldname"		"ItemBackground"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"62"
		"tall"			"62"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"bgcolor_override"		"0 0 0 192"
		"paintbackgroundtype" "2"
		"proportionaltoparent"	"1"
		"roundedcorners"	"0"
	}
		
	"BuildingIcon"	
	{
		"controlname"	"ImagePanel"
		"fieldname"		"BuildingIcon"
		"pin_to_sibling" "ItemNameLabel"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"43"
		"tall"			"43"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		//"icon"			"obj_status_sentrygun_1"
		"drawcolor"		"HudBlack"
	}

	"CantBuildReason"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"CantBuildReason"
		"font"			"MeterLabelFont"
		"fgcolor"		"White"
		"xpos"			"0"
		"ypos"			"21"
		"zpos"			"3"
		"wide"			"62"
		"tall"			"18"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Hud_Menu_Build_Already_Built"
		"textAlignment"	"center"
		"centerwrap"		"1"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	
	"MetalIcon"	
	{
		"controlname"	"ImagePanel"
		"fieldname"		"MetalIcon"
		"pin_to_sibling" "BuildingIcon"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_BOTTOMLEFT"
		"xpos"			"3"
		"ypos"			"-2"
		"zpos"			"1"
		"wide"			"16"
		"tall"			"16"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"image"			"resource/svgs/engineer/ico_metal.svg"
		"drawcolor"		"HudBlack"
	}
	
	"CostLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"CostLabel"
		"font"			"HudFontSmall"
		"pin_to_sibling" "MetalIcon"
		"pin_corner_to_sibling" "PIN_CENTER_LEFT"
		"pin_to_sibling_corner" "PIN_CENTER_RIGHT"
		"fgcolor"		"HudBlack"
		"xpos"			"3"
		"ypos"			"1"
		"zpos"			"1"
		"wide"			"84"
		"tall"			"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"Left"
		"dropshadow"		"1"
		"dropshadowoffset"	"1"
	}
	
	"ModeLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"ModeLabel"
		"font"			"DefaultSmall"
		"fgcolor"		"TanDark"
		"xpos"			"33"
		"ypos"			"17"
		"zpos"			"1"
		"wide"			"44"
		"tall"			"13"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"East"	
	}
		
	"NumberBg"	
	{
		"wide"			"0"
		"tall"			"0"
	}
	
	"NumberLabel"
	{	
		"wide"			"0"
		"tall"			"0"
	}
}