"Resource/UI/build_menu/base.res"
{
	"ItemNameLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"ItemNameLabel"
		"font"			"MeterLabelFont"
		"fgcolor"		"Black"
		"xpos"			"0"
		"ypos"			"2"
		"zpos"			"1"
		"wide"			"62"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Object_Sentry"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
	}

	"ItemBackground"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"ItemBackground"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"62"
		"tall"			"58"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"bgcolor_override"		"White"
		"paintbackgroundtype" "2"
		"proportionaltoparent"	"1"
	}
	
	"BuildingIcon"	
	{
		"controlname"	"CIconPanel"
		"fieldname"		"BuildingIcon"
		"pin_to_sibling" "ItemNameLabel"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"43"
		"tall"			"43"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"icon"			"hud_menu_sentry_build"
		"iconColor"		"255 255 255 255"
	}
	
	"ModeLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"ModeLabel"
		"font"			"DefaultSmall"
		"fgcolor"		"TanDarker"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"5"
		"wide"			"44"
		"tall"			"13"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"textAlignment"	"west"	
	}
	
	"NumberLabel"
	{	
		"controlname"	"CSCHintIcon"
		"fieldname"		"NumberLabel"
		"xpos"			"37"
		"ypos"			"100"
		"zpos"			"1"
		"wide"			"25"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"actionSet"		"InGameHUDControls"
	}
}