"Resource/UI/HudArenaNotification.res"
{
	"HudArenaNotificationBG"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"HudArenaNotificationBG"
		"visible"		"0"
	}
	"ArenaNotificationBG"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"ArenaNotificationBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-1"
		"wide"			"f0"
		"tall"			"28"
		"visible"		"1"
		"image"			"..\darhud\square\square_neutral"
		"teambg_0"		"..\darhud\square\square_neutral"
		"teambg_1"		"..\darhud\square\square_spectator"
		"teambg_2"		"..\darhud\square\square_red"
		"teambg_3"		"..\darhud\square\square_blue"
		"teambg_4"		"..\darhud\square\square_green"
		"teambg_5"		"..\darhud\square\square_yellow"
		"scaleimage"		"1"
	}
	"ArenaNotificationBGShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"ArenaNotificationBGShadow"
		"pin_to_sibling"	"ArenaNotificationBG"
		"xpos"			"0"
		"ypos"			"-2"
		"zpos"			"-2"
		"wide"			"f0"
		"tall"			"28"
		"visible"		"1"
		"image"			"..\darhud\square\square_shadow"
		"scaleimage"		"1"
	}

	"WarningLabel"
	{	
		"controlname"		"Label"
		"fieldname"		"WarningLabel"
		"font"			"ScoreboardTeamScore"
		"xpos"			"35"
		"ypos"			"25"
		"zpos"			"1"
		"wide"			"50"
		"tall"			"50"
		"wide"			"230"
		"tall"			"55"
		"visible"		"0"
		"wrap"			"1"
		"labelText"		"!"
		"textAlignment"	"north"
	}
	"BalanceLabel"
	{	
		"controlname"			"Label"
		"fieldname"			"BalanceLabel"
		"font"				"HudFontSmallBold"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"1"
		"wide"				"f0"
		"tall"				"20"
		"visible"			"1"
		"wrap"				"0"
		"labelText"			""
		"textAlignment"		"center"
		"fgcolor_override"	"ObjectiveLabel"
		"dropshadow"			"1"
		"dropshadowoffset"	"3"
	}

	"BalanceLabelTip"
	{	
		"controlname"			"Label"
		"fieldname"			"BalanceLabelTip"
		"font"				"HudFontSmallest"
		"xpos"				"0"
		"ypos"				"15"
		"zpos"				"1"
		"wide"				"f0"
		"tall"				"14"
		"visible"			"1"
		"labelText"			"%notificationtip%"
		"textAlignment"		"center"
		"fgcolor_override"	"ObjectiveLabel"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"Switchimage"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"Switchimage"
		"xpos"			"25"
		"ypos"			"23"
		"zpos"			"1"
		"wide"			"50"
		"tall"			"50"
		"visible"		"0"
		"image"			"../hud/ico_teambalance"
		"scaleimage"		"1"
	}
	
	"IconLeft"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"	"IconLeft"
		"xpos"		"2"
		"ypos"		"1"
		"wide"		"26"
		"tall"		"26"
		"visible"	"1"
		"image"		"../hud/objectives_flagpanel_ico_flag_moving"
		"scaleimage"	"1"
	}
	
	"IconRight"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"	"IconRight"
		"xpos"		"r27"
		"ypos"		"1"
		"wide"		"26"
		"tall"		"26"
		"visible"	"1"
		"image"		"../hud/objectives_flagpanel_ico_flag_moving"
		"scaleimage"	"1"
	}

}
