"Resource/UI/arenawinpanel.res"
{
	ArenaWinPanel
	{
		"fieldname"		"ArenaWinPanel"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"c-210"
		"ypos"			"0"
		"wide"			"422"
		"tall"			"480"
	}
	"ArenaWinPanelScores"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"ArenaWinPanelScores"
		"proportionaltoparent"	"1"
		"xpos"			"0"
		"ypos"			"78"
		"wide"			"422"
		"tall"			"80"
		"visible"		"1"

		"BlueScoreBG"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"BlueScoreBG"
			"proportionaltoparent"	"1"
			"xpos"			"0"
			"ypos"			"15"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"image"			"..\darhud\square\square_blue"
			"scaleimage"		"1"
			
			if_3team
			{
				"wide"			"140"
			}
			
			if_4team
			{
				"wide"			"105"
			}
		}
		"RedScoreBG"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"RedScoreBG"
			"proportionaltoparent"	"1"
			"xpos"			"210"
			"ypos"			"15"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"image"			"..\darhud\square\square_red"
			"scaleimage"		"1"
			
			if_3team
			{
				"xpos"			"140"
				"wide"			"140"
			}
			
			if_4team
			{
				"xpos"			"105"
				"wide"			"105"
			}
		}
		"GreenScoreBG"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"GreenScoreBG"
			"proportionaltoparent"	"1"
			"xpos"			"0"
			"ypos"			"15"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"image"			"..\darhud\square\square_green"
			"scaleimage"		"1"
			
			if_3team
			{
				"xpos"			"280"
				"wide"			"140"
			}
			
			if_4team
			{
				"xpos"			"210"
				"wide"			"105"
			}
		}
		"YellowScoreBG"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"YellowScoreBG"
			"proportionaltoparent"	"1"
			"xpos"			"210"
			"ypos"			"15"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"image"			"..\darhud\square\square_yellow"
			"scaleimage"		"1"
			
			if_3team
			{
				"xpos"			"140"
				"wide"			"140"
			}
			
			if_4team
			{
				"xpos"			"315"
				"wide"			"105"
			}
		}
		"ScoreBGShadow"
		{
			"controlname"	"ImagePanel"
			"fieldname"	"ScoreBGShadow"
			"proportionaltoparent"	"1"
			"xpos"		"2"
			"ypos"		"17"
			"zpos"		"-1"
			"wide"		"420"
			"tall"		"30"
			"scaleimage"	"1"
			"image"		"..\darhud\square\square_shadow"
		}
		"BlueTeamLabel"
		{
			"controlname"		"CExLabel"
			"fieldname"		"BlueTeamLabel"
			"font"			"ScoreboardTeamName"
			"labelText"		"%blueteamname%"
			"textAlignment"		"west"
			"xpos"			"5"
			"ypos"			"26"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"dropshadow_override"	"1"
			"dropshadowoffset"	"2"
		}							
		"BlueTeamScore"
		{
			"controlname"		"CExLabel"
			"fieldname"		"BlueTeamScore"
			"font"			"HudFontGiantBold"
			"labelText"		"%blueteamscore%"
			"textAlignment"		"east"
			"xpos"			"125"
			"ypos"			"0"
			"zpos"			"3"
			"wide"			"80"
			"tall"			"50"
			"visible"		"1"
			"enabled"		"1"
			"dropshadow_override"	"1"
			"dropshadowoffset"	"3"
			
			if_3team
			{
				"xpos"			"55"
			}
			if_4team
			{
				"xpos"			"20"
			}
		}
		"BlueTeamScoreDropshadow"
		{
			"visible"		"0"
		}							
		"RedTeamLabel"
		{
			"controlname"		"CExLabel"
			"fieldname"		"RedTeamLabel"
			"font"			"ScoreboardTeamName"
			"labelText"		"%redteamname%"
			"textAlignment"		"east"
			"xpos"			"315"
			"ypos"			"26"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"dropshadow_override"	"1"
			"dropshadowoffset"	"2"
			
			if_3team
			{
				"xpos"			"145"
				"textAlignment"		"west"
			}
			
			if_4team
			{
				"xpos"			"110"
				"textAlignment"		"west"
			}
		}							
		"RedTeamScore"
		{
			"controlname"		"CExLabel"
			"fieldname"		"RedTeamScore"
			"font"			"HudFontGiantBold"
			"labelText"		"%redteamscore%"
			"textAlignment"		"west"
			"xpos"			"215"
			"ypos"			"0"
			"zpos"			"3"
			"wide"			"80"
			"tall"			"50"
			"visible"		"1"
			"enabled"		"1"
			"dropshadow_override"	"1"
			"dropshadowoffset"	"3"
			
			if_3team
			{
				"textAlignment"		"east"
			}
			
			if_4team
			{
				"xpos"				"125"
				"textAlignment"		"east"
			}
		}
		"RedTeamScoreDropshadow"
		{
			"visible"		"0"
		}		
		"GreenTeamLabel"
		{
			"controlname"		"CExLabel"
			"fieldname"		"GreenTeamLabel"
			"font"			"ScoreboardTeamName"
			"labelText"		"%greenteamname%"
			"textAlignment"		"west"
			"xpos"			"5"
			"ypos"			"26"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"dropshadow_override"	"1"
			"dropshadowoffset"	"2"
			
			if_3team
			{
				"xpos"			"285"
				"textAlignment"		"west"
			}
			
			if_4team
			{
				"xpos"			"215"
				"textAlignment"		"west"
			}
		}							
		"GreenTeamScore"
		{
			"controlname"		"CExLabel"
			"fieldname"		"GreenTeamScore"
			"font"			"HudFontGiantBold"
			"labelText"		"%greenteamscore%"
			"textAlignment"		"east"
			"xpos"			"125"
			"ypos"			"0"
			"zpos"			"3"
			"wide"			"80"
			"tall"			"50"
			"visible"		"1"
			"enabled"		"1"
			"dropshadow_override"	"1"
			"dropshadowoffset"	"3"
			
			if_3team
			{
				"xpos"			"335"
				"textAlignment"	"east"
			}
			
			if_4team
			{
				"xpos"			"230"
				"textAlignment"	"east"
			}
		}
		"GreenTeamScoreDropshadow"
		{
			"visible"		"0"
		}							
		"YellowTeamLabel"
		{
			"controlname"		"CExLabel"
			"fieldname"		"YellowTeamLabel"
			"font"			"ScoreboardTeamName"
			"labelText"		"%yellowteamname%"
			"textAlignment"		"east"
			"xpos"			"315"
			"ypos"			"26"
			"wide"			"100"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"dropshadow_override"	"1"
			"dropshadowoffset"	"2"
			
			if_3team
			{
				"xpos"			"-5"
				"textAlignment"		"west"
			}
			
			if_4team
			{
				"xpos"			"320"
				"textAlignment"		"west"
			}
		}							
		"YellowTeamScore"
		{
			"controlname"		"CExLabel"
			"fieldname"		"YellowTeamScore"
			"font"			"HudFontGiantBold"
			"labelText"		"%yellowteamscore%"
			"textAlignment"		"west"
			"xpos"			"215"
			"ypos"			"0"
			"zpos"			"3"
			"wide"			"80"
			"tall"			"50"
			"visible"		"1"
			"enabled"		"1"
			"dropshadow_override"	"1"
			"dropshadowoffset"	"3"
			
			if_3team
			{
				"textAlignment"		"east"
			}
			
			if_4team
			{
				"xpos"			"335"
				"textAlignment"		"east"
			}
		}
		"YellowTeamScoreDropshadow"
		{
			"visible"		"0"
		}		

	
		"ArenaStreaksBG"
		{
			"controlname"		"ScalableImagePanel"
			"fieldname"		"ArenaStreaksBG"
			"xpos"			"102"
			"ypos"			"38"
			"zpos"			"2"
			"wide"			"0"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"1"
			
			if_3team
			{
				"xpos"			"135"
				"ypos"			"55"
			}
			
			if_4team
			{
				"xpos"			"135"
				"ypos"			"55"
			}
		}	

		"ArenaStreakLabel"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"ArenaStreakLabel"
			"font"			"HudFontSmallest"
			"fgcolor"		"GeneralLabel"
			"proportionaltoparent"	"1"
			"xpos"			"c-88"
			"ypos"			"42"
			"zpos"			"3"
			"wide"			"176"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%arenastreaktext%"
			"textAlignment"	"center"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
	}

	"WinPanelBG"
	{
		"controlname"		"ImagePanel"
		"fieldname"		"WinPanelBG"
		"xpos"			"25"
		"ypos"			"r125"
		"zpos"			"0"
		"wide"			"370"
		"tall"			"120"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"		"1"
	}
	"WinPanelBGShadow"
	{
		"controlname"		"ImagePanel"
		"fieldname"		"WinPanelBGShadow"
		"xpos"			"27"
		"ypos"			"r123"
		"zpos"			"-1"
		"wide"			"370"
		"tall"			"120"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"		"1"
		"image"			..\darhud\square\square_shadow
	}
	"WinningTeamLabel"
	{	
		"controlname"			"CExLabel"
		"fieldname"			"WinningTeamLabel"
		"font"				"ScoreboardTeamName"
		"xpos"				"25"
		"ypos"				"r123"
		"zpos"				"1"
		"wide"				"370"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"%WinningTeamLabel%"
		"textAlignment"		"center"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"WinningTeamLabelDropshadow"
	{	
		"visible"		"0"
	}

	"LosingTeamLabel"
	{	
		"controlname"			"CExLabel"
		"fieldname"			"WinningTeamLabel"
		"font"				"ScoreboardTeamName"
		"xpos"				"25"
		"ypos"				"r123"
		"zpos"				"1"
		"wide"				"370"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"%LosingTeamLabel%"
		"textAlignment"		"center"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"LosingTeamLabelDropshadow"
	{	
		"visible"		"0"
	}
	"WinReasonLabel"
	{	
		"controlname"			"CExLabel"
		"fieldname"			"WinReasonLabel"
		"font"				"WinPanelDetailsFont"
		"xpos"				"28"
		"ypos"				"r108"
		"zpos"				"1"
		"wide"				"364"
		"tall"				"20"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"%WinReasonLabel%"
		"textAlignment"		"center"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"DetailsLabel"
	{	
		"controlname"			"CExLabel"
		"fieldname"			"DetailsLabel"
		"font"				"WinPanelDetailsFont"
		"xpos"				"28"
		"ypos"				"r94"
		"zpos"				"1"
		"wide"				"364"
		"tall"				"10"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"%DetailsLabel%"
		"textAlignment"		"center"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"ShadedBar"
	{
		"controlname"		"ImagePanel"
		"fieldname"		"ShadedBar"
		"xpos"			"25"
		"ypos"			"r83"
		"zpos"			"2"
		"wide"			"370"
		"tall"			"78"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"	
		"fillcolor"		"0 0 0 150"
		"fillcolor_lodef"		"0 0 0 200"
		"PaintBackgroundType"	"0"
	}
	"TopPlayersLabel"
	{	
		"controlname"		"CExLabel"
		"fieldname"		"TopPlayerLabel"
		"font"			"HudFontSmallest"
		"xpos"			"38"
		"ypos"			"r83"
		"zpos"			"3"
		"wide"			"300"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%TopPlayersLabel%"
		"textAlignment"		"west"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"DamageThisRoundLabel"
	{	
		"controlname"		"CExLabel"
		"fieldname"		"DamageThisRoundLabel"
		"font"			"HudFontSmallest"
		"xpos"			"218"
		"ypos"			"r83"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Arena_Winpanel_DamageThisRound"
		"textAlignment"		"west"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"HealingThisRoundLabel"
	{	
		"controlname"		"CExLabel"
		"fieldname"		"PointsThisRoundLabel"
		"font"			"HudFontSmallest"
		"xpos"			"268"
		"ypos"			"r83"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Arena_Winpanel_HealingThisRound"
		"textAlignment"		"west"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"LifetimeThisRoundLabel"
	{	
		"controlname"		"CExLabel"
		"fieldname"		"PointsThisRoundLabel"
		"font"			"HudFontSmallest"
		"xpos"			"313"
		"ypos"			"r83"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Arena_Winpanel_TimeAliveThisRound"
		"textAlignment"		"west"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"KillingBlowsThisRoundLabel"
	{	
		"controlname"		"CExLabel"
		"fieldname"		"PointsThisRoundLabel"
		"font"			"HudFontSmallest"
		"xpos"			"360"
		"ypos"			"r83"
		"zpos"			"3"
		"wide"			"50"
		"tall"			"20"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Arena_Winpanel_KillingBlows"
		"textAlignment"		"west"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}
	"HorizontalLine"
	{
		"controlname"		"ImagePanel"
		"fieldname"		"HorizontalLine"
		"xpos"			"43"
		"ypos"			"r63"
		"zpos"			"3"
		"wide"			"334"
		"tall"			"1"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"	
		"fillcolor"		"250 234 201 255"
		"PaintBackgroundType"	"0"
		"dropshadow"			"1"
		"dropshadowoffset"	"2"
	}

	"ArenaWinPanelWinnersPanel"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"ArenaWinPanelWinnersPanel"
		"xpos"			"47"
		"ypos"			"r58"
		"wide"			"370"
		"tall"			"218"
		"visible"		"1"
		"zpos"			"3"

		"Player1Avatar"
		{
			"controlname"		"CAvatarImagePanel"
			"fieldname"		"Player1Avatar"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleimage"		"1"
			"color_outline"		"52 48 45 255"
		}
		"Player1Name"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Name"
			"font"					"WinpanelStatsFont"
			"xpos"			"16"
			"ypos"			"-2"
			"wide"			"105"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player1Class"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Class"
			"font"					"WinpanelStatsFont"
			"xpos"			"125"
			"ypos"			"-2"
			"wide"			"200"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player1Damage"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Damage"
			"font"					"WinpanelStatsFont"
			"xpos"			"181"
			"ypos"			"-2"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player1Healing"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Healing"
			"font"					"WinpanelStatsFont"
			"xpos"			"229"
			"ypos"			"-2"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player1Lifetime"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Lifetime"
			"font"					"WinpanelStatsFont"
			"xpos"			"275"
			"ypos"			"-2"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player1Kills"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Kills"
			"font"					"WinpanelStatsFont"
			"xpos"			"300"
			"ypos"			"-2"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Avatar"	
		{
			"controlname"		"CAvatarImagePanel"
			"fieldname"		"Player2Avatar"
			"xpos"			"0"
			"ypos"			"17"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleimage"		"1"
			"color_outline"		"52 48 45 255"
		}
		"Player2Name"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Name"
			"font"					"WinpanelStatsFont"
			"xpos"			"16"
			"ypos"			"15"
			"wide"			"105"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Class"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Class"
			"font"					"WinpanelStatsFont"
			"xpos"			"125"
			"ypos"			"15"
			"wide"			"200"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Damage"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Damage"
			"font"					"WinpanelStatsFont"
			"xpos"			"181"
			"ypos"			"15"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Healing"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Healing"
			"font"					"WinpanelStatsFont"
			"xpos"			"229"
			"ypos"			"15"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Lifetime"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Lifetime"
			"font"					"WinpanelStatsFont"
			"xpos"			"275"
			"ypos"			"15"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Kills"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Kills"
			"font"					"WinpanelStatsFont"
			"xpos"			"300"
			"ypos"			"15"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Avatar"
		{
			"controlname"		"CAvatarImagePanel"
			"fieldname"		"Player3Avatar"
			"xpos"			"0"
			"ypos"			"34"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleimage"		"1"
			"color_outline"		"52 48 45 255"
		}
		"Player3Name"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Name"
			"font"					"WinpanelStatsFont"
			"xpos"			"16"
			"ypos"			"32"
			"wide"			"105"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Class"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Class"
			"font"					"WinpanelStatsFont"
			"xpos"			"125"
			"ypos"			"32"
			"wide"			"200"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Damage"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Damage"
			"font"					"WinpanelStatsFont"
			"xpos"			"181"
			"ypos"			"32"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Healing"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Healing"
			"font"					"WinpanelStatsFont"
			"xpos"			"229"
			"ypos"			"32"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Lifetime"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Lifetime"
			"font"					"WinpanelStatsFont"
			"xpos"			"275"
			"ypos"			"32"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Kills"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Kills"
			"font"					"WinpanelStatsFont"
			"xpos"			"300"
			"ypos"			"32"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
	}
	"ArenaWinPanelLosersPanel"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"ArenaWinPanelLosersPanel"
		"xpos"			"47"
		"ypos"			"r58"
		"wide"			"348"
		"tall"			"218"
		"visible"		"1"
		"zpos"			"3"

		"Player1Avatar"
		{
			"controlname"		"CAvatarImagePanel"
			"fieldname"		"Player1Avatar"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleimage"		"1"
			"color_outline"		"52 48 45 255"
		}
		"Player1Name"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Name"
			"font"					"WinpanelStatsFont"
			"xpos"			"16"
			"ypos"			"-2"
			"wide"			"105"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player1Class"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Class"
			"font"					"WinpanelStatsFont"
			"xpos"			"125"
			"ypos"			"-2"
			"wide"			"200"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player1Damage"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Damage"
			"font"					"WinpanelStatsFont"
			"xpos"			"181"
			"ypos"			"-2"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player1Healing"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Healing"
			"font"					"WinpanelStatsFont"
			"xpos"			"229"
			"ypos"			"-2"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player1Lifetime"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Lifetime"
			"font"					"WinpanelStatsFont"
			"xpos"			"275"
			"ypos"			"-2"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player1Kills"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player1Kills"
			"font"					"WinpanelStatsFont"
			"xpos"			"300"
			"ypos"			"-2"
			"wide"			"30"
			"tall"			"18"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Avatar"	
		{
			"controlname"		"CAvatarImagePanel"
			"fieldname"		"Player2Avatar"
			"xpos"			"0"
			"ypos"			"17"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleimage"		"1"
			"color_outline"		"52 48 45 255"
		}
		"Player2Name"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Name"
			"font"					"WinpanelStatsFont"
			"xpos"			"16"
			"ypos"			"15"
			"wide"			"105"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Class"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Class"
			"font"					"WinpanelStatsFont"
			"xpos"			"125"
			"ypos"			"15"
			"wide"			"200"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Damage"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Damage"
			"font"					"WinpanelStatsFont"
			"xpos"			"181"
			"ypos"			"15"
			"wide"			"30"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Healing"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Healing"
			"font"					"WinpanelStatsFont"
			"xpos"			"229"
			"ypos"			"15"
			"wide"			"30"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Lifetime"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Lifetime"
			"font"					"WinpanelStatsFont"
			"xpos"			"275"
			"ypos"			"15"
			"wide"			"30"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player2Kills"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player2Kills"
		"font"					"WinpanelStatsFont"
			"xpos"			"300"
			"ypos"			"15"
			"wide"			"30"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Avatar"
		{
			"controlname"		"CAvatarImagePanel"
			"fieldname"		"Player3Avatar"
			"xpos"			"0"
			"ypos"			"34"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"image"			""
			"scaleimage"		"1"
			"color_outline"		"52 48 45 255"
		}
		"Player3Name"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Name"
			"font"					"WinpanelStatsFont"
			"xpos"			"16"
			"ypos"			"32"
			"wide"			"105"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Class"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Class"
			"font"					"WinpanelStatsFont"
			"xpos"			"125"
			"ypos"			"32"
			"wide"			"200"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Damage"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Damage"
			"font"					"WinpanelStatsFont"
			"xpos"			"181"
			"ypos"			"32"
			"wide"			"30"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Healing"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Healing"
			"font"					"WinpanelStatsFont"
			"xpos"			"229"
			"ypos"			"32"
			"wide"			"30"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Lifetime"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Lifetime"
			"font"					"WinpanelStatsFont"
			"xpos"			"275"
			"ypos"			"32"
			"wide"			"30"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		"Player3Kills"
		{	
			"controlname"		"CExLabel"
			"fieldname"		"Player3Kills"
			"font"					"WinpanelStatsFont"
			"xpos"			"300"
			"ypos"			"32"
			"wide"			"30"
			"tall"			"20"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"		"east"
			"font"			"WinpanelFont"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
	}
}
