"resource/ui/meters/hudweaponchargemeter.res"
{	
	"ChargeMeter"
	{	
		"controlname"	"ContinuousProgressBar"
		"fieldname"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"3"
		"ypos"			"3"
        "zpos"          "1"
		"wide"			"59"
		"tall"			"5"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
        "bgcolor_override" 		"MeterBackground"
		"fgcolor_override" 		"ProgressOffWhite"
	}

    "ChargeMeterBG"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"ChargeMeterBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"64"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"image"			"..\darhud\meter\meter_spectator"
		"teambg_0"		"..\darhud\meter\meter_neutral"
		"teambg_1"		"..\darhud\meter\meter_spectator"
		"teambg_2"		"..\darhud\meter\meter_red"
		"teambg_3"		"..\darhud\meter\meter_blue"
		"teambg_4"		"..\darhud\meter\meter_green"
		"teambg_5"		"..\darhud\meter\meter_yellow"
		"scaleimage"	"1"
	}

    "ChargeMeterBGShadow"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"ChargeMeterBGShadow"
		"pin_to_sibling" "ChargeMeterBG"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_TOPLEFT"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"-1"
		"wide"			"64"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"image"			"..\darhud\meter\meter_shadow"
		"scaleimage"	"1"
	}
}