"Resource/UI/HudItemEffectMeter_PowerupBottle.res"
{
	"HudItemEffectMeter"
	{
		"fieldname"		"HudItemEffectMeter"
		"xpos"			"r127"
		"xpos_minmode"	"c234"
		"ypos"			"r20"
		"zpos"			"2"
        "wide"			"127"
		"tall"			"20"
	}
	"ItemEffectMeterBG"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"ItemEffectMeterBG"
		"proportionaltoparent"	"1"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"f86"
		"tall"			"f2"
		"image"			"..\darhud\counter\counter_neutral"
		"scaleimage"		"1"
		"teambg_0"		"..\darhud\counter\counter_neutral"
		"teambg_1"		"..\darhud\counter\counter_spectator"
		"teambg_2"		"..\darhud\counter\counter_red"
		"teambg_3"		"..\darhud\counter\counter_blue"
		"teambg_4"		"..\darhud\counter\counter_green"
		"teambg_5"		"..\darhud\counter\counter_yellow"
	}
	"BgShadow"
	{
		"controlname"		"ImagePanel"
		"fieldname"		"BgShadow"
		"pin_to_sibling"	"ItemEffectMeterBG"
		"proportionaltoparent"	"1"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"-1"
		"wide"			"f86"
		"tall"			"f2"
		"image"			"resource/svgs/darhud/counter_mask.svg"
		"scaleimage"		"1"
		"drawcolor"		"HudShadow"
	}
	
	"ItemEffectMeterLabel"
	{
		"controlname"				"CExLabel"
		"fieldname"				"ItemEffectMeterLabel"
		"proportionaltoparent"		"1"
		"textAlignment"			"west"
		"wrap"					"1"
		"proportionaltoparent"		"1"
		"pin_to_sibling"			"ItemEffectMeterBG"
		"pin_corner_to_sibling"	"pin_center_left"
		"pin_to_sibling_corner"	"pin_center_right"
		"xpos"					"2"
		"ypos"					"0"
		"wide"					"f46"
		"tall"					"f0"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				"#TF_PVE_UsePowerup_MinMode"
		"textAlignment"			"center"
		"centerwrap"				"1"
		"font"					"HudFontTiny"
		"dropshadow"				"1"
		"dropshadowoffset"		"2"
	}
	
	// "ItemEffectIconBG"
	// {
		// "controlname"	"ImagePanel"
		// "fieldname"		"ItemEffectIconBG"
		// "xpos"			"5"
		// "ypos"			"2"
		// "zpos"			"2"
		// "wide"			"15"
		// "tall"			"15"
		// "visible"		"1"
		// "enabled"		"1"
		// "scaleimage"	"1"
		// "image"			"resource/svgs/meters/ico_powerup_bottle.svg"
		// "drawcolor"		"ProgressOffWhite"
		// "dropshadow"		"1"
		// "dropshadowoffset"	"2"
	// }
	"ItemEffectIcon"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"ItemEffectIcon"
		"xpos"			"7"
		"ypos"			"3"
		"zpos"			"2"
		"wide"			"13"
		"tall"			"13"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"image"			"../hud/ico_powerup_critboost_red"
		"drawcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}

	"ItemEffectMeter"
	{	
		"controlname"			"ContinuousProgressBar"
		"fieldname"				"ItemEffectMeter"
		"font"					"Default"
		"xpos"					"25"
		"ypos"					"23"
		"zpos"					"2"
		"wide"					"40"
		"tall"					"6"
		"visible"				"0"
		"enabled"				"0"
		"textAlignment"			"Left"
	}
	
	"ItemEffectMeterCount"
	{
		"controlname"	"CExLabel"
		"fieldname"		"ItemEffectMeterCount"
		"font"			"HudFontMediumSmall"
		"labelText"		"%progresscount%"
		"textAlignment" "center"
		"proportionaltoparent"	"1"
		"xpos"			"10"
		"ypos"			"0"
		"wide"			"40"
		"tall"			"18"
		"fgcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
}
