"."
{
	HudItemEffectMeter
	{
		"fieldname"		"HudItemEffectMeter"
		"xpos"			"-2"
		"ypos"			"r20"
		"xpos_minmode" 	"c-360"
		"visible"		"1"
		"enabled"		"1"
		"zpos"			"4"
		"wide"			"60"
		"wide_minmode"	"70"
		"tall"			"19"
		"MeterFG"		"White"
		"MeterBG"		"Gray"
	}
	
	"ItemEffectMeterBG"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"ItemEffectMeterBG"
		"proportionaltoparent"	"1"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"f2"
		"tall"			"f2"
		"visible"		"1"
		"enabled"		"1"
		"image"			"..\darhud\scoreboard\side\score_left_neutral"
		"teambg_0"		"..\darhud\scoreboard\side\score_left_neutral"
		"teambg_1"		"..\darhud\scoreboard\side\score_left_spectator"
		"teambg_2"		"..\darhud\scoreboard\side\score_left_red"
		"teambg_3"		"..\darhud\scoreboard\side\score_left_blue"
		"teambg_4"		"..\darhud\scoreboard\side\score_left_green"
		"teambg_5"		"..\darhud\scoreboard\side\score_left_yellow"
		"scaleimage"	"1"
		
		"image_minmode"			"..\darhud\counter\counter_neutral"
		"teambg_0_minmode"		"..\darhud\counter\counter_neutral"
		"teambg_1_minmode"		"..\darhud\counter\counter_spectator"
		"teambg_2_minmode"		"..\darhud\counter\counter_red"
		"teambg_3_minmode"		"..\darhud\counter\counter_blue"
		"teambg_4_minmode"		"..\darhud\counter\counter_green"
		"teambg_5_minmode"		"..\darhud\counter\counter_yellow"
	}	

	"ItemEffectMeterBGShadow"
	{
		"controlname"	"CTFImagePanel"
		"fieldname"		"ItemEffectMeterBGShadow"
		"pin_to_sibling" "PlayerStatusHealthimageBG"
		"pin_corner_to_sibling" "PIN_CENTER_LEFT"
		"pin_to_sibling_corner" "PIN_CENTER_RIGHT"
		"proportionaltoparent"	"1"
		"xpos"			"2"
		"ypos"			"2"
		"wide"			"f2"
		"tall"			"f2"	
		"zpos"			"-1"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"image"			"..\darhud\scoreboard\side\score_left_shadow"
		"image_minmode"	"..\darhud\counter\counter_shadow"
	}
	
    "Icon"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"Icon"
		"pin_to_sibling" "ItemEffectMeterBG"
		"pin_corner_to_sibling" "PIN_CENTER_LEFT"
		"pin_to_sibling_corner" "PIN_CENTER_LEFT"
		"xpos"			"-4"
		"xpos_minmode"	"-10"
		"ypos"			"2"
		"ypos_minmode"	"0"
		"zpos"			"2"
		"wide"			"10"
		"tall"			"10"
		"visible"		"1"
		"enabled"		"1"
		"image"			"resource/svgs/meters/killstreak.svg"
		"scaleimage"	"1"
		"drawcolor"		"CounterIcon"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}

	"ItemEffectMeterCount"
	{
		"controlname"			"CExLabel"
		"fieldname"				"ItemEffectMeterCount"
		"proportionaltoparent"		"1"
		"pin_to_sibling"			"Icon"
		"pin_corner_to_sibling"	"PIN_CENTER_LEFT"
		"pin_to_sibling_corner"	"PIN_CENTER_RIGHT"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"2"
		"wide"					"f20"
		"wide_minmode"			"f26"
		"tall"					"18"
		"visible"				"1"
		"enabled"				"1"
		"labelText"				"%progresscount%"
		"textAlignment"			"east"
		"textinsetx"				"2"
		"font"					"HudFontMediumSmallSecondary"
		"fgcolor"		        "CounterValue"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}

	"ItemEffectMeterLabel"
	{
		"wide"					"0"
		"tall"					"0"
	}

	"ItemEffectMeter"
	{	
		"controlname"			"ContinuousProgressBar"
		"fieldname"				"ItemEffectMeter"
		"visible"				"0"
		"enabled"				"0"
	}	
}