"Resource/UI/HudObjectiveVIP.res"
{
	"ObjectiveStatusVIP"
	{
		"controlname"		"EditablePanel"
		"fieldname"			"ObjectiveStatusVIP"
		"xpos"				"c-200"
		"ypos"				"60"
		"zpos"				"1"
		"wide"				"400"
		"tall"				"200"
		"visible"			"1"
		"enabled"			"1"
		"progress_xpos"		"79"
		"progress_wide"		"270"
	}

	"LevelBar"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"LevelBar"
		"xpos"			"73"
		"ypos"			"12"
		"zpos"			"0"
		"wide"			"254"
		"tall"			"4"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		""
		"image"			"../darhud/payload/cart_track"
		"scaleimage"	"1"
	}

	"HomeCPIcon"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"HomeCPIcon"
		"xpos"			"59"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"28"
		"tall"			"28"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		""
		"image"			"../darhud/obj_icons/vipr/icon_obj_home_blu"
		"scaleimage"	"1"
	}
	
	"GoalIcon"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"GoalIcon"
		"xpos"			"313"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"28"
		"tall"			"28"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		""
		"image"			"../darhud/obj_icons/vip/icon_obj_car_red"
		"scaleimage"	"1"
	}

	"EscortItemPanel"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"EscortItemPanel"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"28"
		"tall"			"28"
		"visible"		"1"
		"enabled"		"1"

		"EscortItemimageBottom"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"EscortItemimageBottom"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"28"
			"tall"			"28"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		""
			"image"			"../darhud/vipr/vip_blue"
			"scaleimage"	"1"
		}
	
		"EscortItemimageBottomShadow"
		{
			"controlname"	"ImagePanel"
			"fieldname"	"EscortItemimageBottomShadow"
			"pin_to_sibling"	"EscortItemimageBottom"
			"xpos"		"0"
			"ypos"		"0"
			"zpos"		"1"
			"wide"		"28"
			"tall"		"28"
			"visible"	"1"
			"enabled"	"1"
			"image"		"../darhud/vipr/vip_shadow"
			"scaleimage"	"1"
		}
	}
}
