"Resource/UI/HudStalemate.res"
{
	"HudStalemateBG"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"HudStalemateBG"
		"visible"		"0"
	}
	"StalemateBG"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"StalemateBG"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-1"
		"wide"			"320"
		"tall"			"60"
		"visible"		"1"
		"enabled"		"1"
		"image"			"..\darhud\scoreboard\middle\score_middle_shadow"
		"scaleimage"		"1"
	}
	"StalemateLabel"
	{	
		"controlname"		"Label"
		"fieldname"		"StalemateLabel"
		"font"			"HudFontMediumBold"
		"xpos"			"10"
		"ypos"			"5"
		"zpos"			"1"
		"wide"			"300"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"centerwrap"		"1"
		"labelText"		"#TF_teambalanced"
		"textAlignment"	"center"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}
	"ReasonLabel"
	{	
		"controlname"		"Label"
		"fieldname"		"ReasonLabel"
		"font"			"ScoreboardSmall"
		"xpos"			"20"
		"ypos"			"28"
		"zpos"			"1"
		"wide"			"280"
		"tall"			"30"
		"visible"		"1"
		"enabled"		"1"
		"centerwrap"		"1"
		"labelText"		""
		"textAlignment"	"center"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
}
