"Resource/UI/HudTournamentSetup.res"
{
	"HudTournamentSetupBG"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"HudTournamentSetupBG"
		"proportionaltoparent"	"1"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-1"
		"wide"			"f2"
		"tall"			"f2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"image"			"..\darhud\square\square_neutral"
		"scaleimage"		"1"
		"teambg_0"			"..\darhud\square\square_neutral"
		"teambg_1"			"..\darhud\square\square_spectator"
		"teambg_2"			"..\darhud\square\square_red"
		"teambg_3"			"..\darhud\square\square_blue"
		"teambg_4"			"..\darhud\square\square_green"
		"teambg_5"			"..\darhud\square\square_yellow"
		"alpha"				"255"
	}
	"HudTournamentSetupBGShadow"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"HudTournamentSetupBGShadow"
		"proportionaltoparent"	"1"
		"xpos"			"2"
		"ypos"			"2"
		"zpos"			"-2"
		"wide"			"f2"
		"tall"			"f2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"image"			"..\darhud\square\square_shadow"
		"scaleimage"		"1"
	}

	"TournamentSetupLabel"
	{
		"controlname"		"Label"
		"fieldname"		"TournamentSetupLabel"
		"font"			"HudFontSmallBold"
		"fgcolor_override" "GeneralLabel"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"180"
		"tall"			"25"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"labelText"		"%tournamentstatelabel%"
		"textAlignment"		"center"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}

	"TournamentTeamNameLabel"
	{
		"controlname"		"Label"
		"fieldname"		"TournamentTeamNameLabel"
		"font"			"HudFontSmallest"
		"fgcolor_override" "HudBlack"
		"xpos"			"5"
		"ypos"			"24"
		"zpos"			"1"
		"wide"			"170"
		"tall"			"18"
		"visible"		"1"
		"enabled"		"1"
		"wrap"			"0"
		"labelText"		"#Tournament_TeamNamePanel"
		"textAlignment"		"east"
		"textinsetx"		"3"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}

	"TournamentNameEdit"
	{
		"controlname"		"TextEntry"
		"fieldname"		"TournamentNameEdit"
		"xpos"		"5"
		"ypos"		"24"
		"wide"		"170"
		"tall"		"18"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textHidden"		"0"
		"editable"		"1"
		"maxchars"		"5"
		"NumericInputOnly"	"0"
		"unicode"		"0"
		"wrap"			"0"
		"fgcolor_override"		"GeneralLabel"
		"bgcolor_override"	"0 0 0 255"
		"labelText"		"%teamname%"
		"textAlignment"		"west"
		"roundedcorners"	"0"
	}

	"HudTournamentNameBG"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"HudTournamentNameBG"
		"xpos"		"8"
		"ypos"		"28"
		"wide"		"100"
		"tall"		"14"
		"zpos"		"0"
		"visible"	"1"
		"enabled"	"1"
		"fillcolor"	"0 0 0 255"
		"scaleimage"	"1"
	}

	"TournamentNotReadyButton"
	{
		"controlname"	"CExButton"
		"fieldname"		"TournamentNotReadyButton"
		"xpos"		"5"
		"ypos"		"46"
		"wide"		"80"
		"tall"		"14"
		"zpos"		"0"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Tournament_TeamNotReady"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"teamnotready"
		"default"		"1"
		"font"			"HudFontSmallestBold"
		"roundedcorners"	"0"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}

	"TournamentReadyButton"
	{
		"controlname"	"CExButton"
		"fieldname"		"TournamentReadyButton"
		"xpos"		"95"
		"ypos"		"46"
		"wide"		"80"
		"tall"		"14"
		"zpos"		"0"
		"autoResize"	"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Tournament_TeamReady"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"command"		"teamready"
		"default"		"1"
		"font"			"HudFontSmallestBold"
		"roundedcorners"	"0"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
}
