#base "_customizations/info_screen/base.res"

"Resource/UI/MapInfoMenu.res"
{
	"mapinfo"
	{
		"controlname"	"Frame"
		"fieldname"		"mapinfo"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"
		"enabled"		"1"
		"paintBackground"	"0"
	}
	
	"MapInfoTitle"
	{
		"controlname"	"CExLabel"
		"fieldname"		"MapInfoTitle"
		"xpos"			"c-190"
		"ypos"			"125"
		"zpos"			"2"
		"wide"			"200"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%mapname%"
		"textAlignment"	"west"
		"font"			"HudFontMediumSmallBold"
		"fgcolor"		"GeneralLabel"
	}
	
	"MapInfoType"
	{
		"controlname"	"CExLabel"
		"fieldname"		"MapInfoType"
		"xpos"			"c-190"
		"ypos"			"155"
		"zpos"			"2"
		"wide"			"200"
		"tall"			"24"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%gamemode%"
		"textAlignment"	"west"
		"font"			"HudFontSmall"
		"fgcolor"		"GeneralLabel"
	}	
	
	"MapInfoText"
	{
		"controlname"	"CExRichText"
		"fieldname"		"MapInfoText"
		"font"			"HudFontSmallest"
		"xpos"			"c-190"
		"ypos"			"190"
		"zpos"			"3"
		"wide"			"200"
		"tall"			"200"
		"autoResize"	"3"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"paintborder"	"0"
		"textAlignment"	"northwest"
		"fgcolor"		"GeneralLabel"
	}
	
	"Mapimage"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"Mapimage"
		"xpos"			"c0"
		"ypos"			"105"
		"zpos"			"2"
		"wide"			"275"
		"tall"			"275"
		"visible"		"0"
		"enabled"		"1"
		"image"			""
		"scaleimage"	"1"
	}
	
	"Footer"
	{
		"Buttons"
		{
			"BackButton"
			{
				"controlname"	"CExButton"
				"fieldname"		"BackButton"
				"xpos"			"40"
				"ypos"			"r40"
				"zpos"			"6"
				"wide"			"150"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"labelText"		"#TF_Back"
				"textAlignment"	"center"
				"command"		"back"
				"font"			"HudFontSmallBold"
				"roundedcorners"	"0"
				
				"sound_armed"		"ui/buttonrollover.wav"
				"sound_depressed"	"ui/buttonclick.wav"
				"sound_released"	"ui/buttonclickrelease.wav"
				"dropshadow"		"1"
				"dropshadowoffset"	"3"
			}

			"MapInfoBackHintIcon"
			{
				"controlname"	"CSCHintIcon"
				"fieldname"		"MapInfoBackHintIcon"
				"xpos"			"45"
				"ypos"			"r37"
				"zpos"			"7"
				"wide"			"25"
				"tall"			"25"
				"visible"		"1"
				"enabled"		"1"
				"textAlignment"	"Left"
				"actionSet"		"InGameHUDControls"
				"actionName"	"menu_cancel"
			}
	
			"IntroButton"
			{
				"controlname"	"CExButton"
				"fieldname"		"IntroButton"
				"proportionaltoparent"	"1"
				"xpos"			"c-75"
				"ypos"			"0"
				"zpos"			"6"
				"wide"			"150"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"labelText"		"#TF_WatchIntro"
				"textAlignment"	"center"
				"command"		"intro"
				"default"		"1"
				"font"			"HudFontSmallBold"
				"roundedcorners"	"0"
				
				"sound_armed"		"ui/buttonrollover.wav"
				"sound_depressed"	"ui/buttonclick.wav"
				"sound_released"	"ui/buttonclickrelease.wav"
				"dropshadow"		"1"
				"dropshadowoffset"	"3"
			}

			"MapInfoIntroHintIcon"
			{
				"controlname"	"CSCHintIcon"
				"fieldname"		"MapInfoIntroHintIcon"
				"xpos"			"c-45"
				"ypos"			"r37"
				"zpos"			"7"
				"wide"			"25"
				"tall"			"25"
				"visible"		"1"
				"enabled"		"1"
				"labelText"		"Y"
				"textAlignment"	"Left"
				"actionSet"		"InGameHUDControls"
				"actionName"	"menu_toggle_function"
			}
			
			"ContinueButton"
			{
				"controlname"		"CExButton"
				"fieldname"		"ContinueButton"
				"xpos"			"r190"
				"ypos"			"0"
				"zpos"			"6"
				"wide"			"150"
				"tall"			"30"
				"visible"		"1"
				"enabled"		"1"
				"labelText"		"#TF_Continue"
				"textAlignment"		"center"
				"wrap"		"0"
				"command"		"continue"
				"default"		"1"
				"font"			"HudFontSmallBold"
				"roundedcorners"	"0"
				
				"sound_armed"		"ui/buttonrollover.wav"
				"sound_depressed"	"ui/buttonclick.wav"
				"sound_released"	"ui/buttonclickrelease.wav"
				"dropshadow"		"1"
				"dropshadowoffset"	"3"
			}

			"MapInfoContinueHintIcon"
			{
				"controlname"	"CSCHintIcon"
				"fieldname"		"MapInfoContinueHintIcon"
				"xpos"			"r185"
				"ypos"			"r37"
				"zpos"			"7"
				"wide"			"25"
				"tall"			"25"
				"visible"		"1"
				"enabled"		"1"
				"textAlignment"	"Left"
				"actionSet"		"InGameHUDControls"
				"actionName"	"menu_select"
			}
		}
	}
}