"Resource/UI/MvMCreditSubPanel.res"
{	
	"HeaderLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"HeaderLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%header%"
		"textAlignment" "north-west"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"300"
		"tall"			"15"
		"fgcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
		
	"TableBackground"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"TableBackground"
		"xpos"			"0"
		"ypos"			"15"
		"zpos"			"-1"
		"proportionaltoparent"	"1"
		"wide"			"f0"
		"tall"			"f15"
		"visible"		"1"
		"bgcolor_override"		"GeneralBackground"
	}
	
	"CreditRatingLabel"
	{
		"controlname"			"CExLabel"
		"fieldname"			"CreditRatingLabel"
		"font"				"HudFontMediumBold"
		"labelText"			"%rating%"
		"textAlignment"		"center"
		"proportionaltoparent"	"1"
		"pin_to_sibling"		"TableBackground"
		"pin_corner_to_sibling"	"pin_center_right"
		"pin_to_sibling_corner"	"pin_center_right"
		"xpos"				"-5"
		"ypos"				"0"
		"wide"				"0"
		"tall"				"20"
		"auto_wide_tocontents"	"1"
		"fgcolor"			"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	
	"CreditCollectedTextLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CreditCollectedTextLabel"
		"font"			"HudFontSmall"
		"labelText"		"#TF_PVE_Collected"
		"textAlignment" "west"
		"xpos"			"10"
		"ypos"			"16"
		"wide"			"90"
		"tall"			"14"
		"fgcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	
	"CreditCollectedCountLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CreditCollectedCountLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%creditscollected%"
		"textAlignment" "east"
		"pin_to_sibling"		"CreditRatingLabel"
		"pin_corner_to_sibling"	"pin_center_right"
		"pin_to_sibling_corner"	"pin_center_left"
		"xpos"			"5"
		"ypos"			"-12"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"14"
		"fgcolor"		"CreditsGreen"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	
	"CreditMissedTextLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CreditMissedTextLabel"
		"font"			"HudFontSmall"
		"labelText"		"#TF_PVE_Missed"
		"textAlignment" "west"
		"xpos"			"10"
		"ypos"			"28"
		"wide"			"90"
		"tall"			"14"
		"fgcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	
	"CreditMissedCountLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CreditMissedCountLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%creditsmissed%"
		"textAlignment" "east"
		"pin_to_sibling"		"CreditRatingLabel"
		"pin_corner_to_sibling"	"pin_center_right"
		"pin_to_sibling_corner"	"pin_center_left"
		"xpos"			"5"
		"ypos"			"0"
		"xpos"			"20"
		"ypos"			"29"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"14"
		"fgcolor"		"RedSolid"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	
	"CreditBonusTextLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CreditBonusTextLabel"
		"font"			"HudFontSmall"
		"labelText"		"#TF_PVE_Bonus"
		"textAlignment" "west"
		"xpos"			"10"
		"ypos"			"40"
		"wide"			"90"
		"tall"			"14"
		"fgcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	"CreditBonusCountLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CreditBonusCountLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"%creditbonus%"
		"textAlignment" "east"
		"pin_to_sibling"		"CreditRatingLabel"
		"pin_corner_to_sibling"	"pin_center_right"
		"pin_to_sibling_corner"	"pin_center_left"
		"xpos"			"5"
		"ypos"			"13"
		"zpos"			"1"
		"wide"			"100"
		"tall"			"14"
		"fgcolor"		"CreditsGreen"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
}