"Resource/UI/MvMInWorldCurrency.res"
{
	"InWorldCurrencyBG"
	{
		"controlname"		"ImagePanel"
		"fieldname"		"InWorldCurrencyBG"
		"proportionaltoparent"	"1"
		"xpos"			"8"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"f10"
		"tall"			"f2"
		"visible"		"1"
		"enabled"		"1"
		"image"			"resource/svgs/darhud/counter_mask_reverse.svg"
		"scaleimage"		"1"
		"drawcolor"		"221 182 72 250"
	}
	"InWorldCurrencyBGShadow"
	{
		"controlname"		"ImagePanel"
		"fieldname"		"InWorldCurrencyBGShadow"
		"proportionaltoparent"	"1"
		"xpos"			"10"
		"ypos"			"2"
		"zpos"			"2"
		"wide"			"f10"
		"tall"			"f2"
		"visible"		"1"
		"enabled"		"1"
		"image"			"resource/svgs/darhud/counter_mask_reverse.svg"
		"scaleimage"		"1"
		"drawcolor"		"HudShadow"
	}
	
	"MoneyImagePanel"
	{
		"controlname"		"ImagePanel"
		"fieldname"		"MoneyImagePanel"
		"xpos"			"-1"
		"ypos"			"-2"
		"zpos"			"4"
		"wide"			"16"
		"tall"			"16"
		"image"			"resource/svgs/darhud/money.svg"
		"drawcolor"		"AdditionalIcon"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"		"1"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	
	"CurrencyGood"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CurrencyGood"
		"font"			"HudFontSmallBold"
		"fgcolor"		"CreditsGreen"
		"proportionaltoparent"	"1"
		"xpos"			"8"
		"ypos"			"0"
		"zpos"			"4"
		"wide"			"f10"
		"tall"			"f2"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%currency%"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	
	"CurrencyBad"
	{
		"controlname"	"CExLabel"
		"fieldname"		"CurrencyBad"
		"font"			"HudFontSmallBold"
		"fgcolor"		"RedSolid"
		"proportionaltoparent"	"1"
		"xpos"			"8"
		"ypos"			"0"
		"zpos"			"4"
		"wide"			"f10"
		"tall"			"f2"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%currency%"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
}