"Resource/UI/MvMWaveLossPanel.res"
{
	"DarkMask"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"DarkMask"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"1"
		"bgcolor_override"		"0 0 0 210"
	}

	"PanelBackground"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"PanelBackground"
		"xpos"			"cs-0.5"
		"ypos"			"cs-0.5"
		"wide"			"550"
		"tall"			"350"
		"visible"		"1"
		
		"PaintBackgroundType"	"0"
		"border"		"SelectedTabBorderBox"
		"bgcolor_override"	"BackgroundDefault"
	}
	
	"WaveFailHeader"
	{
		"controlname"	"CExLabel"
		"fieldname"		"WaveFailHeader"
		"font"			"HudFontMediumBold"
		"labelText"		"%waveheader%"
		"textAlignment" "center"
		"pin_to_sibling"	"PanelBackground"
		"pin_corner_to_sibling"	"pin_center_top"
		"pin_to_sibling_corner"	"pin_center_top"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"550"
		"tall"			"30"
		"fgcolor"		"GeneralLabel"
	}
	"WaveFailHeaderShadow"
	{
		"controlname"	"CExLabel"
		"fieldname"		"WaveFailHeaderShadow"
		"font"			"HudFontMediumBold"
		"labelText"		"%waveheader%"
		"textAlignment" "center"
		"pin_to_sibling"	"WaveFailHeader"
		"xpos"			"-2"
		"ypos"			"-2"
		"zpos"			"1"
		"wide"			"550"
		"tall"			"30"
		"fgcolor"		"GeneralShadow"
	}
	
	"SummaryHeader"
	{
		"controlname"	"CExLabel"
		"fieldname"		"SummaryHeader"
		"font"			"HudFontMediumSmallBold"
		"labelText"		"%summaryheader%"
		"textAlignment" "west"
		"xpos"			"c-250"
		"ypos"			"90"
		"wide"			"550"
		"tall"			"30"
		"fgcolor"		"GeneralLabel"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
	}
	
	"CollectionContainer"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"CollectionContainer"
		"xpos"			"c-250"
		"ypos"			"120"
		"wide"			"245"
		"tall"			"55"
		"visible"		"1"
		"bgcolor_override"	"GeneralBackground"
		
		"Header"
		{
			"controlname"	"CExLabel"
			"fieldname"		"Header"
			"font"			"HudFontSmallBold"
			"labelText"		"#TF_PVE_Credit_Collection"
			"textAlignment" "west"
			"xpos"			"5"
			"ypos"			"2"
			"wide"			"140"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}
	
		"CollectedLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"CollectedLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Collected"
			"textAlignment" "west"
			"xpos"			"5"
			"ypos"			"16"
			"wide"			"120"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"CollectedCount"
		{
			"controlname"	"CExLabel"
			"fieldname"		"CollectedCount"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditscollected%"
			"textAlignment" "east"
			"xpos"			"205"
			"ypos"			"16"
			"wide"			"30"
			"tall"			"14"
			"fgcolor"		"CreditsGreen"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"MissedLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"MissedLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Missed"
			"textAlignment" "west"
			"xpos"			"5"
			"ypos"			"28"
			"wide"			"120"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"MissedCount"
		{
			"controlname"	"CExLabel"
			"fieldname"		"MissedCount"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditsmissed%"
			"textAlignment" "east"
			"xpos"			"205"
			"ypos"			"28"
			"wide"			"30"
			"tall"			"14"
			"fgcolor"		"RedSolid"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"BonusLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"BonusLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Bonus"
			"textAlignment" "west"
			"xpos"			"5"
			"ypos"			"40"
			"wide"			"120"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"BonusCount"
		{
			"controlname"	"CExLabel"
			"fieldname"		"BonusCount"
			"font"			"HudFontSmallBold"
			"labelText"		"%creditbonus%"
			"textAlignment" "east"
			"xpos"			"205"
			"ypos"			"40"
			"wide"			"30"
			"tall"			"14"
			"fgcolor"		"CreditsGreen"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
	}
	
	"UsageContainer"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"UsageContainer"
		"xpos"			"c5"
		"ypos"			"120"
		"wide"			"245"
		"tall"			"55"
		"visible"		"1"
		"bgcolor_override"	"GeneralBackground"
		
		"Header"
		{
			"controlname"	"CExLabel"
			"fieldname"		"Header"
			"font"			"HudFontSmallBold"
			"labelText"		"#TF_PVE_Credit_Use"
			"textAlignment" "west"
			"xpos"			"5"
			"ypos"			"2"
			"wide"			"140"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}
	
		"YouLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"YouLabel"
			"font"			"FontStorePriceSmall"
			"labelText"		"#TF_PVE_You"
			"textAlignment" "east"
			"xpos"			"150"
			"ypos"			"10"
			"wide"			"35"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"TeamLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"TeamLabel"
			"font"			"FontStorePriceSmall"
			"labelText"		"#Winpanel_Team2"
			"textAlignment" "east"
			"xpos"			"205"
			"ypos"			"10"
			"wide"			"35"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"BuybackLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"BuybackLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Buybacks"
			"textAlignment" "west"
			"xpos"			"5"
			"ypos"			"16"
			"wide"			"160"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"BuybackCountYou"
		{
			"controlname"	"CExLabel"
			"fieldname"		"BuybackCountYou"
			"font"			"HudFontSmallBold"
			"labelText"		"%buybacksyou%"
			"textAlignment" "east"
			"xpos"			"150"
			"ypos"			"16"
			"wide"			"35"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"BuybackCountTeam"
		{
			"controlname"	"CExLabel"
			"fieldname"		"BuybackCountTeam"
			"font"			"HudFontSmallBold"
			"labelText"		"%buybacksteam%"
			"textAlignment" "east"
			"xpos"			"205"
			"ypos"			"16"
			"wide"			"35"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"BottleLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"BottleLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Bottles"
			"textAlignment" "west"
			"xpos"			"5"
			"ypos"			"28"
			"wide"			"160"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"BottleCountYou"
		{
			"controlname"	"CExLabel"
			"fieldname"		"BottleCountYou"
			"font"			"HudFontSmallBold"
			"labelText"		"%bottlesyou%"
			"textAlignment" "east"
			"xpos"			"150"
			"ypos"			"28"
			"wide"			"35"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"BottleCountTeam"
		{
			"controlname"	"CExLabel"
			"fieldname"		"BottleCountTeam"
			"font"			"HudFontSmallBold"
			"labelText"		"%bottlesteam%"
			"textAlignment" "east"
			"xpos"			"205"
			"ypos"			"28"
			"wide"			"35"
			"tall"			"14"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"InactiveLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"InactiveLabel"
			"font"			"HudFontSmall"
			"labelText"		"#TF_PVE_Inactive_Upgrades"
			"textAlignment" "west"
			"xpos"			"5"
			"ypos"			"40"
			"wide"			"160"
			"tall"			"16"
			"fgcolor"		"GeneralLabel"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"InactiveCountYou"
		{
			"controlname"	"CExLabel"
			"fieldname"		"ActiveCountYou"
			"font"			"HudFontSmallBold"
			"labelText"		"%inactiveupgradesyou%"
			"textAlignment" "east"
			"xpos"			"150"
			"ypos"			"40"
			"wide"			"35"
			"tall"			"14"
			"fgcolor"		"RedSolid"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"InactiveCountTeam"
		{
			"controlname"	"CExLabel"
			"fieldname"		"ActiveCountTeam"
			"font"			"HudFontSmallBold"
			"labelText"		"%inactiveupgradesteam%"
			"textAlignment" "east"
			"xpos"			"205"
			"ypos"			"40"
			"wide"			"35"
			"tall"			"14"

			"fgcolor"		"RedSolid"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
	}
	
	"HintContainer"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"HintContainer"
		"xpos"			"c-250"
		"ypos"			"180"
		"wide"			"500"
		"tall"			"180"
		"visible"		"1"
		"bgcolor_override"	"GeneralBackground"
		
		"Header"
		{
			"controlname"	"CExLabel"
			"fieldname"		"Header"
			"font"			"HudFontSmallBold"
			"labelText"		"#TF_PVE_Hint_Header"
			"textAlignment" "center"
			"xpos"			"0"
			"ypos"			"3"
			"wide"			"500"
			"tall"			"16"
			"fgcolor"		"Gray"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}

		"CptCntnBody"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"CptCntnBody"
			"xpos"		"5"
			"ypos"		"70"
			"zpos"		"2"
			"wide"		"50"
			"tall"		"50"
			"image"			""
			"visible"		"0"
			"enabled"		"1"
			"scaleimage"		"1"
		}

		"CptCntnMisc"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"CptCntnMisc"
			"xpos"		"5"
			"ypos"		"45"
			"zpos"		"3"
			"wide"		"50"
			"tall"		"50"
			"image"			""
			"visible"		"0"
			"enabled"		"1"
			"scaleimage"		"1"
		}

		"CptCntnHat"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"CptCntnHat"
			"xpos"		"5"
			"ypos"		"20"
			"zpos"		"1"
			"wide"		"50"
			"tall"		"50"
			"image"			""
			"visible"		"0"
			"enabled"		"1"
			"scaleimage"		"1"
		}
		
		"Hintimage1"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"Hintimage1"
			"proportionaltoparent"	"1"
			"xpos"		"5"
			"ypos"		"cs-0.5"
			"wide"		"50"
			"tall"		"100"
			"image"			"class_sel_sm_engineer_inactive"
			"visible"		"1"
			"enabled"		"1"
			"scaleimage"		"1"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"Hint1"
		{
			"controlname"	"CExLabel"
			"fieldname"		"Hint1"
			"font"			"HudFontSmallest"
			"labelText"		"%hint1%"
			"textAlignment" "west"
			"proportionaltoparent"	"1"
			"xpos"			"55"
			"ypos"			"cs-0.5"
			"wide"			"200"
			"tall"			"55"
			"fgcolor"		"Gray"
			"wrap"			"1"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"Hintimage2"
		{
			"controlname"		"ImagePanel"
			"fieldname"		"Hintimage2"
			"proportionaltoparent"	"1"
			"xpos"		"255"
			"ypos"		"cs-0.5"
			"wide"		"50"
			"tall"		"100"
			"image"			"class_sel_sm_engineer_inactive"
			"visible"		"1"
			"enabled"		"1"
			"scaleimage"		"1"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
		
		"Hint2"
		{
			"controlname"	"CExLabel"
			"fieldname"		"Hint2"
			"font"			"HudFontSmallest"
			"labelText"		"%hint2%"
			"textAlignment" "west"
			"proportionaltoparent"	"1"
			"xpos"			"305"
			"ypos"			"cs-0.5"
			"wide"			"200"
			"tall"			"55"
			"fgcolor"		"Gray"
			"wrap"			"1"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
	}
	
	"VoteButton"
	{
		"controlname"	"CEximageButton"
		"fieldname"		"VoteButton"
		"xpos"			"c-250"
		"ypos"			"370"
		"zpos"			"999"
		"wide"			"200"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_PVE_Vote_MissionRestart"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"default"		"1"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		
		"roundedcorners"	"0"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
		
		"Command"		"vote_restart"
	}
		
	"ContinueButton"
	{
		"controlname"	"CEximageButton"
		"fieldname"		"ContinueButton"
		"xpos"			"c150"
		"ypos"			"370"
		"zpos"			"1000"
		"wide"			"100"
		"tall"			"25"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#ConfirmButtonText"
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"default"		"1"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		
		"roundedcorners"	"0"
		"dropshadow"		"1"
		"dropshadowoffset"	"3"
		
		"Command"		"continue"
	}
}