"Resource/UI/Spectator.res"
{
	"Spectator"
	{
		"controlname"		"Frame"
		"fieldname"		"Spectator"
		"tall"			"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"specgui"
	{
	}
	"topbar"
	{
		"controlname"		"Panel"
		"fieldname"		"TopBar"
		"xpos"			"0"
		"ypos"			"0"
		"tall"			"45"
		"wide"			"f0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"alpha"			"0"
	}
	
	"topbarblank"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"topbardark"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-1"
		"tall"			"45"
		"wide"			"f0"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"paintBackground"	"1"
		"bgcolor_override"	"20 20 20 255"
	}
	
	"BottomBar"
	{
		"controlname"	"Frame"
		"fieldname"		"BottomBar"
		"xpos"			"0"
		"ypos"			"r70"
		"ypos_minmode"	"r20"
		"tall"			"70"
		"tall_minmode"	"0"		
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"0"
		"tabPosition"		"0"
	}
	"bottombarblank"
	{
		"controlname"		"Panel"
		"fieldname"		"bottombarblank"
		"xpos"			"0"
		"ypos"			"r0"
		"ypos_minmode"	"r0"
		"tall"			"70"	// this needs to match the size of BottomBar
		"wide"			"f0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"visible_minmode"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"ReinforcementsLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"ReinforcementsLabel"
		"fgcolor_override"		"GeneralLabel"
		"xpos"			"cs-0.5"
		"ypos"			"68"
		"wide"			"300"
		"tall"			"16"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#game_respawntime_in_secs"
		"textAlignment"		"center"
		"font"			"HudFontSmall"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}

	"BuyBackLabel"
	{
		"controlname"	"CExLabel"
		"fieldname"		"BuyBackLabel"
		"xpos"			"cs-0.5"
		"ypos"			"2"
		"zpos"			"1"
		"wide"			"f0"
		"tall"			"16"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_PVE_Buyback"
		"textAlignment"	"center"
		"font"			"HudFontSmallBold"
		"bgcolor_override"	"GreenSolid"
		"fgcolor"	"GeneralLabel"
		"paintBackgroundType" "0"
		"wrap"			"1"
		"centerwrap"	"1"
		"dropshadow"			"1"
		"dropshadowoffset"		"3"
	
		if_mvm
		{
			"visible"		"1"
		}
	}
	"MapLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"MapLabel"
		"font"			"HudFontSmall"
		"fgcolor_override"		"GeneralLabel"
		"xpos"			"15"
		"ypos"			"0"
		"wide"			"240"
		"tall"			"44"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"		"west"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	"ClassOrTeamLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"ClassOrTeamLabel"
		"xpos"			"c-85"
		"ypos"			"68"
		"wide"			"170"
		"tall"			"15"
		"zpos"			"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Spectator_ChangeTeam"
		"textAlignment"		"center"
		"textAlignment_lodef"		"north-west"
		"font"			"SpectatorKeyHints"
		"font_hidef"	"HudFontSmallest"
		"font_lodef"	"HudFontSmall"
		"wrap_lodef"			"1"
	}
	"SwitchCamModeKeyLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"SwitchCamModeKeyLabel"
		"fgcolor_override"		"GeneralLabel"
		"xpos"			"5"
		"ypos"			"r95"
		"wide"			"60"
		"auto_wide_tocontents"	"1"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"visible_minmode"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Spectator_ChangeTeam"
		"textAlignment"		"west"
		"font"			"HudFontSmallestBold"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	"SwitchCamModeLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"SwitchCamModeLabel"
		"fgcolor_override"		"GeneralLabel"
		"xpos"			"55"
		"ypos"			"r95"	
		"wide"			"125"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"visible_minmode"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Spectator_SwitchCamMode"
		"textAlignment"		"west"
		"font"			"HudFontSmallest"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	
	"CycleTargetFwdKeyLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"CycleTargetFwdKeyLabel"
		"fgcolor_override"		"GeneralLabel"
		"xpos"			"5"
		"ypos"			"r85"
		"wide"			"60"
		"auto_wide_tocontents"	"1"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"visible_minmode"		"0"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Spectator_ClassOrTeamKey"
		"textAlignment"		"west"
		"font"			"HudFontSmallestBold"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	"CycleTargetFwdLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"CycleTargetFwdLabel"
		"fgcolor_override"		"GeneralLabel"
		"xpos"			"55"
		"ypos"			"r85"	
		"wide"			"125"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"visible_minmode"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Spectator_CycleTargetFwd"
		"textAlignment"		"west"
		"font"			"HudFontSmallest"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	"CycleTargetRevKeyLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"CycleTargetRevKeyLabel"
		"fgcolor_override"		"GeneralLabel"
		"xpos"			"5"
		"ypos"			"r75"
		"wide"			"60"
		"auto_wide_tocontents"	"1"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"visible_minmode"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Spectator_ClassOrTeamKey"
		"textAlignment"		"west"
		"font"			"HudFontSmallestBold"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}
	"CycleTargetRevLabel"
	{
		"controlname"		"CExLabel"
		"fieldname"		"CycleTargetRevLabel"
		"fgcolor_override"		"GeneralLabel"
		"xpos"			"55"
		"ypos"			"r75"
		"wide"			"125"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"visible_minmode"		"0"
		"enabled"		"1"
		"labelText"		"#TF_Spectator_CycleTargetRev"
		"textAlignment"		"west"
		"font"			"HudFontSmallest"
		"dropshadow"		"1"
		"dropshadowoffset"	"2"
	}

	"TipContainer"
	{
		"controlname"	"EditablePanel"
		"fieldname"	"TipContainer"
		"xpos"		"5"
		"ypos"		"r45"
		"wide"		"250"
		"tall"		"40"
		"visible"			"1"
		"visible_minmode"		"0"
		
		"Tipimage"
		{
			"controlname"			"CTFImagePanel"
			"fieldname"				"Tipimage"
			"xpos"					"0"
			"ypos"					"0"
			"zpos"					"12"
			"wide"					"40"
			"tall"					"40"
			"visible"				"0"
			"enabled"				"1"
			"scaleimage"			"1"
		}
		
		"TipText"
		{
			"controlname"		"CExLabel"
			"fieldname"		"TipText"
			"fgcolor_override"		"GeneralLabel"
			"xpos"			"50"
			"ypos"			"0"
			"wide"			"200"
			"tall"			"40"
			"visible"		"1"
			"labelText"		""
			"textAlignment"		"west"
			"font"			"TipFont"
			"wrap"			"1"
			"dropshadow"		"1"
			"dropshadowoffset"	"2"
		}
	}
	
	"spectator_extras"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"spectator_extras"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"480"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
	}
	
	"crosshair"
	{
		"controlname"		"CTFImagePanel"
		"fieldname"		"crosshair"
		"xpos"			"cs-0.5"
		"ypos"			"cs-0.5"
		"zpos"			"0"
		"wide"			"1"
		"tall"			"1"
		"visible"		"1"
		"enabled"		"1"
		"alpha"			"128"
	}	
}
