"Resource/training/main.res"
{
	"TrainingDialog"
	{
		"controlname"	"CTrainingDialog"
		"fieldname"		"TrainingDialog"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"f0"
		"tall"		"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"bgcolor_override"	"0 0 0 127"
	}
	"whitebg"
	{
		"controlname"		"EditablePanel"
		"fieldname"		"whitebg"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-133"
		"wide"			"f0"
		"tall"			"480"
		"bgcolor_override"	"255 255 255 255"
		"visible"		"0"
	}
	"Header"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"Header"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"f0"
		"tall"		"p0.09"
		"proportionaltoparent"	"1"
		
		"HeaderBackground"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"HeaderBackground"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"-2"
			"wide"			"f0"
			"tall"			"f0"
			"visible"		"1"
			"enabled"		"1"
			"image"			"../darhud/mainmenu/striped_pattern"
			"drawcolor"		"BackgroundDefault"
			"tileimage"		"1"
		}
		
		"HeaderLine"
		{
			"controlname"	"EditablePanel"
			"fieldname"		"HeaderLine"
			"xpos"			"0"
			"ypos"			"r2"
			"zpos"			"5"
			"wide"			"f0"
			"tall"			"2"
			"proportionaltoparent"	"1"
			"visible"		"1"
			"enabled"		"1"
			"bgcolor_override"	"ButtonMM"
			"scaleimage"	"1"
		}
		
		"Title"
		{
			"controlname"		"Label"
			"fieldname"		"Title"
			"xpos"		"cs-0.5"
			"ypos"		"rs1"
			"wide"		"620"
			"tall"		"26"
			"textAlignment"	"north-west"
			"proportionaltoparent"	"1"
			"font"			"HudFontMediumBold"
			"use_proportional_insets"	"1"
			"textinsety"	"0"
			"textinsetx"	"0"
			"labelText"	"#TR_PracticeModeSelectTitle"
			"mouseinputenabled"	"0"
			"proportionaltoparent"	"1"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}
	}
			
	"ContainerShadow"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"ContainerShadow"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"50"
		"tall"			"f0"
		"zpos"			"-1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		
		"RoundedCorners" "0"
		"PaintBackgroundType"	"3"
		"paintbackground"	"1"
		"bgcolor_override"	"0 0 0 240"
		
		"FadeAlphaStart"	"0"
		"FadeAlphaEnd"	"255"
		
		"pin_to_sibling"	"ContainerShadowMid"
		"pin_corner_to_sibling"		"pin_topright"
		"pin_to_sibling_corner"	"pin_topleft"
	}
	
	"ContainerShadow2"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"ContainerShadow2"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"50"
		"tall"			"f0"
		"zpos"			"-1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		
		"RoundedCorners" "0"
		"PaintBackgroundType"	"3"
		"paintbackground"	"1"
		"bgcolor_override"	"0 0 0 240"
		
		"FadeAlphaStart"	"255"
		"FadeAlphaEnd"	"0"
		
		"pin_to_sibling"	"ContainerShadowMid"
		"pin_corner_to_sibling"		"pin_topleft"
		"pin_to_sibling_corner"	"pin_topright"
	}
	
	"ContainerShadowMid"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"ContainerShadowMid"
		"xpos"			"cs-0.5"
		"ypos"			"0"
		"wide"			"460"
		"tall"			"f0"
		"zpos"			"-1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		
		"RoundedCorners" "0"
		"paintbackground"	"1"
		"bgcolor_override"	"0 0 0 240"
	}

	"Container"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"Container"
		"xpos"		"c-225"
		"ypos"		"c-200"
		"zpos"		"0"
		"wide"		"450"
		"tall"		"400"
		"visible"		"1"
		"enabled"		"1"
		"PaintBackgroundType"	"0"
		"paintbackground"		"1"
		"border"				"NoBorder"
		
		"GradientBgPanel"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"GradientBgPanel"
			"xpos"			"10"
			"ypos"			"135"
			"zpos"			"1"
			"wide"			"0"
			"tall"			"0"
			"visible"		"0"
			"tileimage"		"0"
			"scaleimage"	"1"
			"image"			"training/gradient"
			"border"		"ButtonBorder"
			"paintbackgroundtype"	"2"
			"paintbackground"	"1"
		}

		"Background"
		{
			"controlname"	"EditablePanel"
			"fieldname"		"Background"
			"xpos"		"0"
			"ypos"		"0"
			"wide"		"450"
			"tall"		"500"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"1"
			"tabPosition"		"0"
			"bgcolor_override"	"MainMenuBackground"
		}

		"TitleLabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"TitleLabel"
			"font"			"HudFontMediumBold"
			"labelText"		"#TR_PracticeModeSelectTitle"
			"textAlignment"	"center"
			"xpos"			"0"
			"ypos"			"15"
			"zpos"			"1"
			"wide"			"450"
			"tall"			"20"
			"autoResize"	"1"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"1"
		}

		"BackButton"
		{
			"controlname"	"CExButton"
			"fieldname"		"BackButton"
			"ypos"			"368"
			"zpos"			"20"
			"wide"			"100"
			"tall"			"25"
			"visible"		"0"
			"enabled"		"1"
			"labelText"		"#TF_BackCarat"
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"textinsetx"	"50"
			"RoundedCorners"	"0"
			"Command"		"prevpage"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}	
		
		"CancelButton"
		{
			"controlname"	"CExButton"
			"fieldname"		"CancelButton"
			"ypos"			"368"
			"zpos"			"20"
			"wide"			"100"
			"tall"			"25"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"#Cancel"
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"textinsetx"	"50"
			"RoundedCorners"	"0"
			"Command"		"cancel"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}
		
		"ModeSelectionPanel"
		{
			"controlname"		"CModeSelectionPanel"
			"fieldname"			"ModeSelectionPanel"
			"xpos"				"0"
			"ypos"				"80"
			"zpos"				"2"
			"wide"				"500"
			"tall"				"400"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"paintBackground"	"0"
			
			"TrainingTitle"		"#TF_Training_Title"
		}
		
		"BasicTraining_ClassSelectionPanel"
		{
			"controlname"		"CBasicTraining_ClassSelectionPanel"
			"fieldname"			"BasicTraining_ClassSelectionPanel"
			"xpos"				"10"
			"ypos"				"80"
			"zpos"				"2"
			"wide"				"430"
			"tall"				"400"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"0"
			"enabled"			"1"
			"tabPosition"		"0"
			"paintBackground"	"0"
			
			"TrainingTitle"		"#TR_AttackDefense"
			"TrainingSubTitle"	"#TF_SelectAClass"
				
			"Class0Token"		"#TF_Soldier"
			"Class1Token"		"#TF_Demoman"
			"Class2Token"		"#TF_Spy"
			"Class3Token"		"#TF_Engineer"
			
			"Class0image"		"training/class_soldier"
			"Class1image"		"training/class_demoman"
			"Class2image"		"training/class_spy"
			"Class3image"		"training/class_engineer"
			
			"Class0Command"		"basictraining_classselection_soldier"
			"Class1Command"		"basictraining_classselection_demoman"
			"Class2Command"		"basictraining_classselection_spy"
			"Class3Command"		"basictraining_classselection_engineer"
		}
		
		"BasicTraining_ClassDetailsPanel"
		{
			"controlname"		"CBasicTraining_ClassDetailsPanel"
			"fieldname"			"BasicTraining_ClassDetailsPanel"
			"xpos"				"0"
			"ypos"				"80"
			"zpos"				"2"
			"wide"				"450"
			"tall"				"500"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"0"
			"enabled"			"1"
			"tabPosition"		"0"
			"paintBackground"	"0"
			
			"TrainingTitle"		"#TR_AttackDefense"
		}
		
		"OfflinePractice_ModeSelectionPanel"
		{
			"controlname"		"COfflinePractice_ModeSelectionPanel"
			"fieldname"			"OfflinePractice_ModeSelectionPanel"
			"xpos"				"0"
			"ypos"				"50"
			"wide"				"450"
			"tall"				"500"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"0"
			"enabled"			"1"
			"tabPosition"		"0"
			"paintBackground"	"0"
			
			"TrainingTitle"		"#TR_PracticeModeSelectTitle"
			
			"Mode0Token"		"#Gametype_VIP"
			"Desc0Token"		"#TF_GameModeDesc_VIP"
			"image0Path"		"illustrations/gamemode_vip"
			"Mode0Id"			"3"
			
			"Mode1Token"		"#Gametype_Domination"
			"Desc1Token"		"#TF_GameModeDesc_Domination"
			"image1Path"		"illustrations/gamemode_domination"
			"Mode1Id"			"4"
			
			"Mode2Token"		"#Gametype_Koth"
			"Desc2Token"		"#TF_GameModeDesc_Koth"
			"image2Path"		"illustrations/gamemode_koth"
			"Mode2Id"			"1"
			
			"Mode3Token"		"#Gametype_CP"
			"Desc3Token"		"#TF_GameModeDesc_CP"
			"image3Path"		"illustrations/gamemode_cp"
			"Mode3Id"			"0"

			"Mode4Token"		"#Gametype_Escort"
			"Desc4Token"		"#TF_GameModeDesc_Escort"
			"image4Path"		"illustrations/gamemode_payload"
			"Mode4Id"			"2"
			
			"Mode5Token"		"#Gametype_Arena"
			"Desc5Token"		"#TF_GameModeDesc_Arena"
			"image5Path"		"illustrations/gamemode_arena"
			"Mode5Id"			"5"
		}
		
		"OfflinePractice_MapSelectionPanel"
		{
			"controlname"		"COfflinePractice_MapSelectionPanel"
			"fieldname"		"OfflinePractice_MapSelectionPanel"
			"xpos"			"0"
			"ypos"			"50"
			"wide"			"450"
			"tall"			"500"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"1"
			"tabPosition"		"0"
			"paintBackground"	"0"
			
			"TrainingTitle"	"#TR_PracticeMapSelectTitle"
		}
	}
}