"Resource/UI/destroy_menu/base_active.res"
{
	"ItemNameLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"ItemNameLabel"
		"font"			"MeterLabelFont"
		"fgcolor"		"White"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"62"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#TF_Object_Sentry"
		"textAlignment"	"center"
		"dropshadow"		"1"
		"dropshadowoffset"	"1"
	}
	
	"ItemBackground"	
	{
		"controlname"	"EditablePanel"
		"fieldname"		"ItemBackground"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"62"
		"tall"			"62"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"bgcolor_override"		"15 15 15 255"
		"paintbackgroundtype" "2"
		"proportionaltoparent"	"1"
		"roundedcorners"	"0"
	}
	
	"DestroyIcon"	
	{
		"controlname"	"CIconPanel"
		"fieldname"		"DestroyIcon"
		"pin_to_sibling" "ItemNameLabel"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"2"
		"zpos"			"1"
		"wide"			"43"
		"tall"			"43"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"icon"			"ico_demolish"
		"iconColor"		"162 60 60 255"
	}
		
	"BuildingIcon"	
	{
		"controlname"	"ImagePanel"
		"fieldname"		"BuildingIcon"
		"pin_to_sibling" "ItemNameLabel"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"2"
		"wide"			"43"
		"tall"			"43"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"image"			"obj_status_sentrygun_1"
		"drawcolor"		"White"
	}
		
	"NumberBg"	
	{
		"controlname"	"CIconPanel"
		"fieldname"		"NumberBg"
		"pin_to_sibling" "BuildingIcon"
		"pin_corner_to_sibling" "PIN_CENTER_TOP"
		"pin_to_sibling_corner" "PIN_CENTER_BOTTOM"
		"xpos"			"0"
		"ypos"			"1"
		"zpos"			"0"
		"wide"			"11"
		"tall"			"11"
		"visible"		"1"
		"enabled"		"1"
		"scaleimage"	"1"
		"icon"			"ico_key_blank"
		"iconColor"		"255 255 255 255"
	}
	
	"NumberLabel"
	{	
		"controlname"	"CExLabel"
		"fieldname"		"NumberLabel"
		"pin_to_sibling" "NumberBg"
		"font"			"FontStorePrice"
		"fgcolor"		"Black"
		"xpos"			"0"
		"ypos"			"1"
		"zpos"			"5"
		"wide"			"11"
		"tall"			"11"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"1"
		"textAlignment"	"Center"
		"dulltext"		"1"
		"brighttext"	"0"
	}
}