"Resource/UI/ItemModelPanel.res"
{	
	"mouseoveritempanel"
	{
		"fieldname"				"mouseoveritempanel"
		"collection_list_xpos"	"250"
		"is_mouseover"			"1"
		"text_xpos_collection"	"0"
		"text_ypos"			"15"
		"text_forcesize" "0"
		"text_xpos"		"15"
		"text_wide"		"270"
		//"model_xpos_collection"	"77"
		//"model_ypos_collection"	"20"
		//"model_wide_collection"	"156"
		//"model_tall_collection"	"100"
	}
	
	"LoadingSpinner"
	{
		"controlname"	"ImagePanel"
		"fieldname"		"LoadingSpinner"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"		
		"wide"			"f0"
		"tall"			"f0"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"paintborder"	"0"
		"image"			"animated/tf2_logo_hourglass"
		"scaleimage"	"1"
		"mouseinputenabled"	"0"
	}

	"MainContentsContainer"
	{
		"controlname"	"EditablePanel"
		"fieldname"		"MainContentsContainer"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"f0"
		"visible"		"1"
		"bgcolor_override"		"0 0 0 0"

		"itemmodelpanel"
		{
			"controlname"		"CEmbeddedItemModelPanel"
			"fieldname"		"itemmodelpanel"
	
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"1"		
			"wide"			"140"
			"tall"			"100"
			"autoResize"		"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"useparentbg"		"1"
		
			"inset_eq_x"	"2"
			"inset_eq_y"	"2"

			"fov"			"54"
			"start_framed"		"1"

			"disable_manipulation"	"1"

			"model"
			{
				"angles_x"		"10"
				"angles_y"		"130"
				"angles_z"		"0"
				"spotlight" "1"
			}
		}
	
		"namelabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"namelabel"
			"font"			"ItemFontNameLarge"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"2"
			"wide"			"140"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%itemname%"
			"textAlignment"	"south"
			"fgcolor"		"235 226 202 255"
			"centerwrap"	"1"
			"dropshadow"		"1"
			"dropshadowoffset"	"3"
		}
		"attriblabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"attriblabel"
			"font"			"ItemFontAttribLarge"
			"xpos"			"0"
			"ypos"			"30"
			"zpos"			"2"
			"wide"			"140"
			"tall"			"60"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"%attriblist%"
			"textAlignment"	"south"
			"fgcolor"		"117 107 94 255"
			"centerwrap"	"1"
			//the drop shadow copies the text colour for some reason
			"dropshadow"		"0"
			"dropshadowoffset"	"1"
		}
		"equippedlabel"
		{
			"controlname"			"CExLabel"
			"fieldname"			"equippedlabel"
			"font"				"FontStorePrice"
			"xpos"				"0"
			"ypos"				"0"
			"zpos"				"2"
			"wide"				"60"
			"tall"				"16"
			"visible"			"1"
			"enabled"			"1"
			"labelText"			"#ItemPanelEquipped"
			"textAlignment"		"center"
			"fgcolor"			"200 80 60 255"
			"PaintBackgroundType"	"2"
			"Border"				"EquippedBG"
			"dropshadow"			"1"
			"dropshadowoffset"	"2"
		}

		"matcheslabel"
		{
			"controlname"	"CExLabel"
			"fieldname"		"matcheslabel"
			"font"			"ItemFontAttribSmall"
			"xpos"			"4"
			"ypos"			"4"
			"zpos"			"2"
			"wide"			"20"
			"tall"			"10"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"0"
			"enabled"		"1"
			"labelText"		""
			"textAlignment"	"center"
			"fgcolor"		"200 180 60 255"
			"bgcolor_override"		"0 40 30 255"
			"PaintBackgroundType"	"2"
		}

		"vision_restriction_icon"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"vision_restriction_icon"
			"xpos"			"4"
			"ypos"			"4"
			"zpos"			"2"
			"autoResize"	"0"
			"pinCorner"		"0"
			"wide"			"16"
			"tall"			"16"
			"visible"		"0"
			"enabled"		"1"
			"scaleimage"	"1"
		}
		"is_strange_icon"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"is_strange_icon"
			"xpos"			"4"
			"ypos"			"4"
			"zpos"			"2"
			"autoResize"	"0"
			"pinCorner"		"0"
			"wide"			"16"
			"tall"			"16"
			"visible"		"0"
			"enabled"		"1"
			"scaleimage"	"1"
		}
		"is_unusual_icon"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"is_unusual_icon"
			"xpos"			"4"
			"ypos"			"4"
			"zpos"			"2"
			"autoResize"	"0"
			"pinCorner"		"0"
			"wide"			"16"
			"tall"			"16"
			"visible"		"0"
			"enabled"		"1"
			"scaleimage"	"1"
		}

		"is_loaner_icon"
		{
			"controlname"	"ImagePanel"
			"fieldname"		"is_loaner_icon"
			"xpos"			"4"
			"ypos"			"4"
			"zpos"			"2"
			"autoResize"	"0"
			"pinCorner"		"0"
			"wide"			"16"
			"tall"			"16"
			"visible"		"0"
			"enabled"		"1"
			"scaleimage"	"1"
		}
		
		"contained_item_panel"
		{
			"controlname"	"CItemModelPanel"
			"xpos"			"32"
			"ypos"			"20"
			"zpos"			"4"
			"wide"			"18"
			"tall"			"18"
			"visible"		"0"
			"bgcolor_override"		"0 0 0 200"
			"noitem_textcolor"		"117 107 94 255"
			"PaintBackgroundType"	"2"
			"paintborder"	"0"
			"useparentbg"	"0"
		
			"enabled"		"1"
		
			"model_xpos"	"1"
			"model_ypos"	"1"
			"model_wide"	"16"
			"model_tall"	"16"
			"text_ypos"		"60"
			"text_center"	"1"
			"model_only"	"1"
		
			"inset_eq_x"	"2"
			"inset_eq_y"	"2"
		
			"itemmodelpanel"
			{
				"use_item_rendertarget" "0"
				"allow_rot"				"0"
			}
		
			"use_item_sounds"	"1"
		}
	}
}
